<?php /* @var $this SM_XPayment_Block_Info_XpaymentMultiple */ ?>
<?php
$arrayNotShow = array('method', 'enable', 'check_date', 'checks');
$emi = $this->getEmi();
?>
<?php if(count($emi)>1){?>
    <strong>Payment with 2C2P: </strong></br>
    <?php
    if(Mage::getStoreConfig('xpos/general/storeid') === null){
        $currentStoreId = Mage::app()->getStore()->getId();
    }else{
        $currentStoreId = Mage::helper('xpos/product')->getCurrentSessionStoreId();
    }
    $currentCurrencyCode = Mage::getStoreConfig('currency/options/default',$currentStoreId);
    foreach ($emi as $k => $v) {?>
        <?php echo $k . ': ' . $v . '</br>'; ?>
        <?php
    }
    ?>
<?php }else{ ?>
    <?php foreach ($emi as $k => $v) { ?>
        <?php if (!in_array($k, $arrayNotShow)) echo ($this->getConfigDataPaymentMethod($k, "title")) . ': ' . Mage::app()->getLocale()->currency($currentCurrencyCode)->toCurrency(floatval($v)) . '</br>'; ?>
        <?php
    }
    ?>
<?php } ?>
