<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Sidebar_Recentpost $this */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
<div class="block mpblog-recentposts">
    <div class="block-title">
        <strong><span><?php echo $this->__('What to read next'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="mpblog-post-grid mbplog-recent-posts">
        <?php foreach ($collection as $post): ?>
            <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
            <?php $categories = $this->getCategories($post->getId());?>
            <li class="post-item  <?php if ($post->getIsActive()): ?> active<?php endif; ?> mpblog-recent-post-<?php echo $post->getId(); ?> fix-me">
                <?php if ($post->getListThumbnailSrc()): ?>
                  <a class="post-image"
                      href="<?php echo $post->getPostUrl(); ?>"
                      title="<?php echo $this->escapeHtml($post->getTitle()); ?>">
                      <img class="thumbnail"
                           src="<?php echo $post->getListThumbnailSrc(); ?>"
                           alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                  </a>
                <?php endif; ?>
                <p class="post-cat">
                  <?php foreach($categories as $category):  ?>
                    <a href="<?php echo $category->getUrl() ?>" title="<?php echo $category->getName(); ?>"><?php echo $category->getName(); ?></a>
                  <?php endforeach; ?>
                </p>
                <div class="post-views-time">
                    <?php if (Mage::helper('mpblog')->getDisplayViews()): ?>
                      <?php
                        if($post->getViews()){
                          $_views = $post->getViews(); 
                        }else{
                          $_views =0;
                        }
                        
                      ?>
                      <span class="post-views"><strong><?php echo $_views; ?></strong><?php echo $this->__('Views') ?></span> 
                    <?php endif; ?>
                    <?php if ($this->showDate()): ?>
                    <span class="post-time">
                        <?php echo $this->renderDate($post->getCreatedAt()); ?>
                    </span>
                    <?php endif; ?>
                </div>   
                <h4 class="post-title">
                  <a href="<?php echo $post->getPostUrl(); ?>" title="<?php echo $this->escapeHtml($post->getTitle()); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                </h4>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
