<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */


/** @var Magpleasure_Blog_Block_Sidebar_Tag $this  */
/** @var Magpleasure_Blog_Model_Mysql4_Tag_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
<div class="block mpblog-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('Tags') ?></span></strong>
    </div>
    <div class="block-content">
        <?php if ($this->getMtEnabled()): ?>
        <div id="mpblog_canvas_container" class="noSwipe">
            <canvas height="<?php echo $this->getMtHeight(); ?>" id="mpblog_canvas">
                <p><?php echo $this->__("Unfortunately, your browser doesn't support HTML5 canvas."); ?></p>
            </canvas>
        </div>
        <?php endif; ?>
        <div id="mpblog_tags" class="tag-list <?php if ($this->getMtEnabled()): ?> cloud-enabled<?php endif; ?>">
            <ul>
                <?php foreach ($collection as $tag): ?>
                <li>
                    <?php /** @var Magpleasure_Blog_Model_Tag $tag */ ?>

                    <a href="<?php echo $tag->getTagUrl(); ?>" class="tag tag<?php echo $this->getTagSizeClass($tag); ?><?php if ($this->isActive($tag)): ?> active<?php endif; ?>" title="<?php echo $this->__("%s Topics", $tag->getPostCount()); ?>"  ><?php echo $this->escapeHtml($tag->getName()); ?></a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <?php if ($this->getMtEnabled()): ?>
    <script type="text/javascript">
        //<![CDATA[

        document.observe('dom:loaded', function() {
            try {
                var options = {
                    weight: true,
                    weightMode: 'both',
                    textHeight: 16,
                    textColour: '#<?php echo $this->getMtTextColor(); ?>',
                    outlineColour: '#<?php echo $this->getMtHiColor(); ?>',
                    weightGradient: {
                        0: '#<?php echo $this->getMtTextColor(); ?>',
                        1: '#<?php echo $this->getMtTextColor2(); ?>'
                    }
                };

                TagCanvas.Start('mpblog_canvas', 'mpblog_tags', options);
            } catch(e) {
                // something went wrong, hide the canvas container
                document.getElementById('mpblog_canvas_container').style.display = 'none';
            }
        });
        //]]>
    </script>
    <?php endif; ?>

</div>
<?php endif; ?>
