<?php
$Imagehome_grid = 0;
$id = $this->getRequest()->getParam('id');
$Imagehomes = Mage::helper('imagehome')->getImagehome($id);
if ($Imagehomes->getImagehomeGrid()) {
    $Imagehome_grid = $Imagehomes->getImagehomeGrid();
}
?>

<div class="container-fluid content-header">
    <div class="icon-head head-adminhtml-imagehome">
        <button style="display: none" data-bind="click: addNewWidget" id="newwidget">Add new widget</button>
        <button  style="display: none" data-bind="click: save" id="savewidget">Save widget</button>
    </div>
    <br>
    <div data-bind="component: {name: 'dashboard-grid_', params: $data}"></div>
</div>

<style type="text/css">
    .grid-stack {
        background: lightgoldenrodyellow;
    }

    .grid-stack-item-content {
        color: #2c3e50;
        text-align: center;
        border: #18bc9c 1px solid;
    }
</style>
<script type="text/javascript">

    var $jqs = jQuery.noConflict();

    ko.components.register('dashboard-grid_', {
        viewModel: {
            createViewModel: function (controller, componentInfo) {
                var ViewModel = function (controller, componentInfo) {
                    var grid = null;

                    this.widgets = controller.widgets;

                    this.afterAddWidget = function (items) {
                        if (grid == null) {
                            grid = $jqs(componentInfo.element).find('.grid-stack').gridstack({
                                auto: false
                            }).data('gridstack');
                        }

                        var item = _.find(items, function (i) {
                            return i.nodeType == 1
                        });
                        grid.addWidget(item);
                        ko.utils.domNodeDisposal.addDisposeCallback(item, function () {
                            grid.removeWidget(item);
                        });
                    };
                };

                return new ViewModel(controller, componentInfo);
            }
        },
        template: {element: 'gridstack-template'}
    });

    $jqs(function () {
        var Controller = function (widgets) {
            var self = this;
            this.widgets = ko.observableArray(widgets);
            this.addNewWidget = function () {
                //alert(ko.utils.stringifyJson(self.widgets));
                var obj = ko.utils.stringifyJson(this.widgets()[widgets.length - 1]['index'])
                var index = parseInt(obj) + 1
                this.widgets.push({
                    x: 0,
                    y: 0,
                    width: Math.floor(1 + 3 * Math.random()),
                    height: Math.floor(1 + 3 * Math.random()),
                    index: index,
                    auto_position: true
                });
                return false;
            };
            this.deleteWidget = function (item) {
                self.widgets.remove(item);
                return false;
            };
            self.save = function (item) {



                var obj = this.widgets();


                this.widgets = _.map($jqs('.grid-stack > .grid-stack-item:visible'), function (el) {
                    el = $jqs(el);
                    var node = el.data('_gridstack_node');

                    return {
                        id: el.attr('data-custom-id'),
                        x: node.x,
                        y: node.y,
                        width: node.width,
                        height: node.height,
                    };
                }, this)
                var imagegrif = [];
                for (var i = 0; i < widgets.length; i++) {
                    var str = ko.utils.stringifyJson(self.widgets[i]);
                    var j = ko.utils.stringifyJson(obj[i]['index'])
                    var grid = str.replace('}', ',"index" :' + j + '}');

                    imagegrif.push(grid);
                }
                $('imagehome_grid').value = imagegrif;
            };
        };
        if (<?php echo $Imagehome_grid ?> == 0) {
            var widgets = [
                {x: 0, y: 0, width: 2, height: 2, image: 'Desert.jpg', index: 1},
                {x: 2, y: 0, width: 4, height: 2, image: 'Desert.jpg', index: 2},
                {x: 6, y: 0, width: 2, height: 4, image: 'Desert.jpg', index: 3},
                {x: 1, y: 2, width: 4, height: 2, image: 'Desert.jpg', index: 4}
            ];
        } else {
            var widgets = <?php echo $Imagehome_grid ?>;
        }



        var controller = new Controller(widgets);
        ko.applyBindings(controller);
    });


    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                input.next().src = e.target.result;
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    $j('magebuzz_mage').value = "['Saab', 'Volvo', 'BMW']";
</script>


<template id="gridstack-template">
    <div class="grid-stack" data-bind="foreach: {data: widgets, afterRender: afterAddWidget}">
        <div class="grid-stack-item" data-bind="attr: {'data-gs-x': $data.x, 'data-gs-y': $data.y, 'data-gs-width': $data.width, 'data-gs-height': $data.height, 'data-gs-auto-position': $data.auto_position , 'data-index' : $data.index} ">
            <div class="grid-stack-item-content">
                <button data-bind="click: $root.deleteWidget" style="float: right;background: none;border: none !important;">
                    <img id="aw_popup_close_btn"  src="http://carnivalbkk.mgfdev.com/skin/frontend/carnival/default/popup/images/close_label.gif">
                </button>
                <input type='file'  data="magebuzz_mage" name="magebuzz_mage[]" id="magebuzz-image" onchange="readURL(this);" />
                <img   data-bind=" attr: { 'src': '<?php echo Mage::getBaseUrl('media'); ?>magebuzz\/' + $data.image  }"  style="width: 100%;height: 100%;position: absolute;z-index: -10;margin: 0;padding: 0;left: 0;top: 0;" src="" alt="your image" />
                <textarea  data-bind='text: $data.html' id="magebuzz_html"  name="magebuzz_html[]" style="float: left;width: 100%;" placeholder="html"></textarea>
            </div>
        </div></div><!-- <---- NO SPACE BETWEEN THESE CLOSING TAGS -->
</template>

<input type="hidden"  name="imagehome_grid" id="imagehome_grid" width="100%" />



