<?php
$check = 0;
$helper = Mage::helper('countingdown');
$categorys = $helper->getCategorys();
foreach ($categorys as $category) {

  $_startTimeStamp = Mage::getModel('core/date')->timestamp($helper->getStartTime($category));
  $products = Mage::getModel('catalog/category')->load($category->getEntityId())
          ->getProductCollection();
  if ($_startTimeStamp && $products->getSize()) {

    $_currentTimestamp = $helper->getCurrentTimestamp();
    $countingup_ = $_startTimeStamp - $_currentTimestamp;
    ?>
    <?php if ($countingup_ > 0) { ?>
      <div class="home-banner-main">
      <div class="cate-upcoming slider-mobile cate-size<?php echo $products->getSize() ?>" >
        <div class="upcoming-title">
          <div>
            <div class="title">
              <h3>
                <?php echo $this->__('Upcoming') ?>
              </h3>
              <p>
                <?php $_descriptionStripped = $category->getDescription(); ?>
                <?php
                if (iconv_strlen($_descriptionStripped, 'UTF-8') > 40) {
                  $_descriptionStripped = iconv_substr($_descriptionStripped, 0, 40, 'UTF-8');
                  $_descriptionStripped .= '...';
                }
                ?>
                <?php echo $_descriptionStripped ?>
                <a target="_blank" href="<?php echo Mage::getUrl('countingdown'); ?>" title="<?php echo $this->__('view all') ?>"><?php echo $this->__('view all') ?></a>
              </p>
            </div>
            <div class="<?php echo $countingup_ ?>"></div>
          </div>
        </div>

        <ul class="products-grid products-grid--max-5-col first last odd" id="products-grid-<?php echo $countingup_ ?>">
          <?php
          $i = 0;
          foreach ($products as $product) {
            $productdetail = Mage::getModel('catalog/product')->load($product->getEntityId());
            $productList = Mage::getBlockSingleton('catalog/product_list');

            $visibility = $productdetail->getVisibility();
            if ($visibility == 2 || $visibility == 3 || $visibility == 4) {
              if ($i++ == 10)
                break;
              $check = 1;
              $productMediaConfig = Mage::getModel('catalog/product_media_config');
              $SmallImageUrl = $productdetail->getSmallImageUrl();
              $Nameproduct = $productdetail->getName();
              $Price = $productdetail->getPrice();
              ?>
              <li class="item last">
                <a class="product-image" title="<?php echo $Nameproduct; ?>" href="<?php echo $productdetail->getProductUrl() ?>">
                  <?php echo Mage::helper('amlabel')->getLabels($productdetail, 'category'); ?>

                  <?php $_imgSize = 300; ?>

                  <img class="img-baseimage" id="product-collection-image-<?php echo $productdetail->getId(); ?>"
                       src="<?php echo Mage::helper('bannerads')->getBaseImage($productdetail)->resize($_imgSize); ?>"
                       alt="<?php echo $this->stripTags($this->getImageLabel($productdetail, 'small_image'), null, true) ?>" />

                  <img class="img-smallimage" id="product-collection-image-small-<?php echo $productdetail->getId(); ?>"
                       src="<?php echo $this->helper('catalog/image')->init($productdetail, 'small_image')->resize($_imgSize); ?>"
                       alt="<?php echo $this->stripTags($this->getImageLabel($productdetail, 'small_image'), null, true) ?>" />

                </a>
                <div class="product-info">

                  <div class="">
                    <h2 class="product-name">
                      <a href="<?php echo $productdetail->getProductUrl() ?>" title="<?php echo $Nameproduct; ?>">
                        <?php $_productNameStripped = $Nameproduct; ?>
                        <?php
                        if (iconv_strlen($_productNameStripped, 'UTF-8') > 20) {
                          $_productNameStripped = iconv_substr($_productNameStripped, 0, 20, 'UTF-8');
                          $_productNameStripped .= '...';
                        }
                        ?>
                        <?php echo $_productNameStripped ?>
                      </a>
                    </h2>
                    <?php
                    if ($productdetail->getData('brands')):
                      $brandName = $productdetail->getResource()->getAttribute('brands')->getFrontend()->getValue($productdetail);
                      ?>
                      <div class="product-brand"><?php echo $brandName; ?></div>
                    <?php endif; ?>
                  </div>
                  <div class="">
                    <?php echo $productList->getPriceHtml($productdetail, true) ?>
                  </div>
                </div>
              </li>
            <?php } ?>
            <?php
          }
          ?>
        </ul>
      </div>
        </div>
    <?php } ?>
    <script type="text/javascript">
      var clock;
      var time = <?php echo $countingup_; ?>;
      var clock;
      if (time > 0 && <?php echo $check ?> == 1) {
        clock = $j('.<?php echo $countingup_ ?>').FlipClock({
          clockFace: 'DailyCounter',
          autoStart: false,
          callbacks: {
            stop: function () {
              location.reload();
            }
          }
        });
        clock.setTime(time);
        clock.setCountdown(true);
        clock.start();
      }
    <?php if ($products->getSize() > 1): ?>
        if (jQuery(window).width() < 700) {
          jQuery('#products-grid-<?php echo $countingup_ ?>').bxSlider({
            pager: false,
            infiniteLoop: false,
            hideControlOnEnd: true,
            controls: true,
            slideMargin: 10,
            slideWidth: 200,
            maxSlides: 2,
            minSlides: 2
          });
        }
    <?php endif; ?>
    </script>
    <?php
  }
  if ($check == 1) {
    break;
  }
}
?>

