<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

?>
<?php if (count($this->getCategories())): ?>
    <span class="categories">
        <?php echo $this->__("Posted in: "); ?>
        <?php $isFirst = true; ?>
        <?php foreach ($this->getCategories() as $category): ?><?php if (!$isFirst): ?>,&nbsp;<?php endif
            ?><a href="<?php echo $category->getCategoryUrl(); ?>"><?php
            echo $this->escapeHtml($category->getName());
            ?></a><?php $isFirst = false; ?><?php
        endforeach; ?>
    </span>
<?php endif; ?>