<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Content_Search_Query $this */
?>

<div class="search-query fix-me">
<!--    <form id="mp_blog_content_search " action="--><?php //echo $this->getSearchUrl(); ?><!--" method="get">-->
<!--        <div class="input-box">-->
<!--            <input-->
<!--                type="text"-->
<!--                placeholder="--><?php //echo $this->getBlockHeader(); ?><!--"-->
<!--                class="input-text required-entry placeholder"-->
<!--                title="--><?php //echo $this->getBlockHeader(); ?><!--"-->
<!--                id="search-blog" name="query"-->
<!--                value="--><?php //echo $this->getQuery(); ?><!--"-->
<!--                maxlength="100" />-->
<!---->
<!--            <button class="button" title="--><?php //echo $this->__("Search"); ?><!--" type="submit">-->
<!--                <i class="glyphicons search --><?php //echo $this->getColorClass(); ?><!--"></i>-->
<!--            </button>-->
<!--        </div>-->
<!--    </form>-->
    <?php if ($this->hasSuggestion()): ?>
    <div class="advice">
        <?php echo $this->__("Did you mean?"); ?>
        <em>
        <?php foreach ($this->getWords() as $word): ?>
            <?php /** @var Magpleasure_Searchcore_Model_Suggestion_Word $word */ ?>
            <?php if ($word->getIsMistyped()): ?>
                <a href="<?php echo $this->getGetSuggestedQueryUrl($word); ?>" title="<?php echo $word->getQuery(); ?>"><?php echo $word->getSuggestValue(); ?></a>
            <?php else: ?>
                <?php echo $word->getOrigValue(); ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </em>
    </div>
    <?php endif; ?>


    <script type="text/javascript">
        //<![CDATA[
        new VarienForm('mp_blog_content_search');
        //]]>
    </script>

</div>