<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

?>
<?php if ($this->getTags()->getSize()): ?>
    <span class="mp-tags">
    <?php $isFirst = true; ?>
    <?php foreach ($this->getTags() as $tag): ?><?php if (!$isFirst): ?>,
    <?php endif ?><a href="<?php echo $tag->getTagUrl(); ?>">#<?php echo $this->escapeHtml($tag->getName()); ?></a><?php $isFirst = false; ?><?php endforeach; ?>
    </span>
<?php endif; ?>