<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Common
 */

/** @var $this Magpleasure_Common_Block_Widget_Dialog_Wrapper */
?>
<?php $dialogs = $this->getDialogs(); ?>

<?php if (count($dialogs)): ?>

<div class="mp-dialog-container" id="mp-dialog-container" style="display: none;">
    <div class="mp-dialog-wrapper" id="mp-dialog-wrapper">
        <div class="mp-dialog-content" id="mp-dialog-content"></div>
    </div>
</div>

<script type="text/javascript">
    <?php foreach ($dialogs as $dialog): ?>
    var <?php echo $dialog->getName(); ?> = new MpWidgetDialog({
        'overlay': 'mp-dialog-overlay',
        'loader': 'mp-dialog-loader',
        'dialog-container': 'mp-dialog-container',
        'dialog-content': 'mp-dialog-content',
        'window_url': '<?php echo $this->getWindowUrl($dialog); ?>',
        'post_url': '<?php echo $this->getPostUrl($dialog); ?>',
        'width': '<?php echo $this->getWidth($dialog); ?>',
        'height': '<?php echo $this->getHeight($dialog); ?>',
        'forward_data': '<?php echo $this->getForwardData($dialog); ?>',
        'error_message': '<ul class="messages"><li class="error-msg"><ul><li><span><?php echo $this->__("Can not load this window. Please try again later."); ?></span></li></ul></li></ul>',
        'additional_data': ''
    });
    <?php endforeach; ?>
</script>
<?php endif; ?>
