<?php
    /** @var $this Cybersource_Cybersource_Block_SOPWebMobile_Form_Payform */
    $_code = $this->getMethodCode();
    $cybersourceCgiUrl = $this->getCybersourceUrl();
?>

<iframe id="cybersourcesop-echeck-iframe" allowtransparency="true" frameborder="0" style="display:none;width:100%;background-color:transparent" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
<form id="co-cybersourcesop-echeck-form" action="<?php echo $cybersourceCgiUrl; ?>" method="post">
    <dl class="sp-methods">
        <dt class="a-center"><?php echo $this->__('ECheck Information') ?></dt>
        <dd>
            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <ul class="form-list cs-form-list" id="payment_form_<?php echo $_code ?>">
                <li>
                    <label for="<?php echo $_code ?>_echeck_routing"
                           class="required"><em>*</em><?php echo $this->__('Routing Number') ?></label>
                    <div class="input-box">
                        <input id="<?php echo $_code ?>_echeck_routing" type="text" title="<?php echo $this->__('Routing Number') ?>" name="payment[routing_number]" value="" class="input-text required-entry" />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_echeck_act"
                           class="required"><em>*</em><?php echo $this->__('Account Number') ?></label>
                    <div class="input-box">
                        <input id="<?php echo $_code ?>_echeck_act" type="text" title="<?php echo $this->__('Account Number') ?>" name="payment[account_number]" value="" class="input-text required-entry" />
                    </div>
                </li>
            </ul>
        </dd>
    </dl>
</form>

<script type="text/javascript">
    new Validation('co-cybersourcesop-echeck-form');
    new cybersourceSopPost(
        'co-cybersourcesop-echeck-form',
        '<?php echo $_code ?>',
        '<?php echo $this->getUrl('cybersource/sopwm/loadSignedFields', array('_secure' => $this->getRequest()->isSecure())) ?>',
        false
    );
</script>
