<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Model_Mysql4_Comment_Collection $collection  */
$collection = $this->getCollection();
?>

<div class="mpblog-comments-livestream" id="livestream">
    <?php if ($collection->getSize()): ?>
        <?php foreach ($collection as $message): ?>
            <?php echo $this->getMessageHtml($message); ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="mp-comment-form" id="form" style="display: none;"></div>
</div>
<div id="mpblog_loader_container" style="display: none;">
    <div class="mp-blog-loader"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var blogComments = new MpBlogComments({
        form_selector: '.mp-comment-form',
        loader_container: 'mpblog_loader_container',
        form_url: '<?php echo $this->getFormUrl() ?>',
        post_url: '<?php echo $this->getPostUrl() ?>',
        post_id: '<?php echo $this->getPostId(); ?>',
        session_id: '<?php echo $this->getSessionId(); ?>',
        comments_counter: 'comments_counter'
    });
//]]>
</script>