<?php
/**
 * @category    Bubble
 * @package     Bubble_DynamicCategory
 * @version     2.4.2
 * @copyright   Copyright (c) 2015 BubbleShop (https://www.bubbleshop.net)
 */
/**
 * @var $this Mage_Adminhtml_Block_Template
 */
?>
<?php echo $this->getChildHtml('dynamic_category_conditions_import') ?>
<div id="category_dynamic_products_conds">
    <?php echo $this->getChildHtml('dynamic_category_conditions') ?>
</div>