SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

INSERT INTO `directory_country_region` (`region_id`, `country_id`, `code`, `default_name`, `sync_id`) VALUES
(485, 'TH', 'Bangkok', 'กรุงเทพมหานคร', NULL),
(486, 'TH', 'Krabi', 'กระบี่', NULL),
(487, 'TH', 'Kanchana Buri', 'กาญจนบุรี', NULL),
(488, 'TH', 'Kalasin', 'กาฬสินธุ์', NULL),
(489, 'TH', 'Kamphaeng Phet', 'กำแพงเพชร', NULL),
(490, 'TH', 'Khon Kaen', 'ขอนแก่น', NULL),
(491, 'TH', 'Chantha Buri', 'จันทบุรี', NULL),
(492, 'TH', 'Cha Choeng Sao', 'ฉะเชิงเทรา', NULL),
(493, 'TH', 'Chon Buri', 'ชลบุรี', NULL),
(494, 'TH', 'Chai Nat', 'ชัยนาท', NULL),
(495, 'TH', 'Chaiyaphum', 'ชัยภูมิ', NULL),
(496, 'TH', 'Chumphon', 'ชุมพร', NULL),
(497, 'TH', 'Chiang Rai', 'เชียงราย', NULL),
(498, 'TH', 'Chiang Mai', 'เชียงใหม่', NULL),
(499, 'TH', 'Trang', 'ตรัง', NULL),
(500, 'TH', 'Trat', 'ตราด', NULL),
(501, 'TH', 'Tak', 'ตาก', NULL),
(502, 'TH', 'Nakhon Nayok', 'นครนายก', NULL),
(503, 'TH', 'Nakhon Pathom', 'นครปฐม', NULL),
(504, 'TH', 'Nakhon Phanom', 'นครพนม', NULL),
(505, 'TH', 'Nakhon Rajcha Sima', 'นคราชสีมา', NULL),
(506, 'TH', 'Nakhon Sri Thamaraj', 'นครศรีธรรมราช', NULL),
(507, 'TH', 'Nakhon Sawan', 'นครสวรรค์', NULL),
(508, 'TH', 'Nontha Buri', 'นนทบุรี', NULL),
(509, 'TH', 'Nara Thiwat', 'นราธิวาส', NULL),
(510, 'TH', 'Nan', 'น่าน', NULL),
(511, 'TH', 'Buri Ram', 'บุรีรัมย์', NULL),
(512, 'TH', 'Pathum Thani', 'ปทุมธานี', NULL),
(513, 'TH', 'Prachuap Khiri Khan', 'ประจวบคีรีขันธ์', NULL),
(514, 'TH', 'Prachin Buri', 'ปราจีนบุรี', NULL),
(515, 'TH', 'Pattani', 'ปัตตานี', NULL),
(516, 'TH', 'Phra Nakhon Sri Ayutthaya', 'พระนครศรีอยุธยา', NULL),
(517, 'TH', 'Phayao', 'พะเยา', NULL),
(518, 'TH', 'Phang Nga', 'พังงา', NULL),
(519, 'TH', 'Phatthalung', 'พัทลุง', NULL),
(520, 'TH', 'Phichit', 'พิจิตร', NULL),
(521, 'TH', 'Phit Sanulok', 'พิษณุโลก', NULL),
(522, 'TH', 'Phetcha Buri', 'เพชรบุรี', NULL),
(523, 'TH', 'Phetchabun', 'เพชรบูรณ์', NULL),
(524, 'TH', 'Phrae', 'แพร่', NULL),
(525, 'TH', 'Phuket', 'ภูเก็ต', NULL),
(526, 'TH', 'Maha Sarakham', 'มหาสารคาม', NULL),
(527, 'TH', 'Muk Dahan', 'มุกดาหาร', NULL),
(528, 'TH', 'Mae Hong Son', 'แม่ฮ่องสอน', NULL),
(529, 'TH', 'Ya Sothon', 'ยโสธร', NULL),
(530, 'TH', 'Yala', 'ยะลา', NULL),
(531, 'TH', 'Roi Et', 'ร้อยเอ็ด', NULL),
(532, 'TH', 'Ranong', 'ระนอง', NULL),
(533, 'TH', 'Rayong', 'ระยอง', NULL),
(534, 'TH', 'Rajcha Buri', 'ราชบุรี', NULL),
(535, 'TH', 'Lop Buri', 'ลพบุรี', NULL),
(536, 'TH', 'Lampang', 'ลำปาง', NULL),
(537, 'TH', 'Lamphun', 'ลำพูน', NULL),
(538, 'TH', 'Loei', 'เลย', NULL),
(539, 'TH', 'Si Saket', 'ศรีสะเกษ', NULL),
(540, 'TH', 'Sakon Nakhon', 'สกลนคร', NULL),
(541, 'TH', 'Songkhla', 'สงขลา', NULL),
(542, 'TH', 'Satun', 'สตูล', NULL),
(543, 'TH', 'Samut Prakan', 'สมุทรปราการ', NULL),
(544, 'TH', 'Samut Songkhram', 'สมุทรสงคราม', NULL),
(545, 'TH', 'Samut Sakhon', 'สมุทรสาคร', NULL),
(546, 'TH', 'Sra Kiao', 'สระแก้ว', NULL),
(547, 'TH', 'Sara Buri', 'สระบุรี', NULL),
(548, 'TH', 'Sing Buri', 'สิงห์บุรี', NULL),
(549, 'TH', 'SuKhothai', 'สุโขทัย', NULL),
(550, 'TH', 'Suphan Buri', 'สุพรรณบุรี', NULL),
(551, 'TH', 'Surat Thani', 'สุราษฎร์ธานี', NULL),
(552, 'TH', 'Surin', 'สุรินทร์', NULL),
(553, 'TH', 'Nongkai', 'หนองคาย', NULL),
(554, 'TH', 'Nong Bua Lumphu', 'หนองบัวลำภู', NULL),
(555, 'TH', 'Ang Thong', 'อ่างทอง', NULL),
(556, 'TH', 'Amnat Charoen', 'อำนาจเจริญ', NULL),
(557, 'TH', 'Udon Thani', 'อุดรธานี', NULL),
(558, 'TH', 'Utta Radit', 'อุตรดิตถ์', NULL),
(559, 'TH', 'Uthai Thani', 'อุทัยธานี', NULL),
(560, 'TH', 'Ubon Rajchathani', 'อุบลราชธานี', NULL);
SET FOREIGN_KEY_CHECKS=1;