
<link rel="icon" href="http://www.magestore.com/skin/frontend/default/magestore61/favicon.ico" type="image/x-icon">

<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery-1.10.2.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery-migrate-1.2.1.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.jeditable.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.jeditable.autogrow.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.autogrow.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.ajaxfileupload.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.jeditable.ajaxupload.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery-ui-1.10.4.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/jquery.contextmenu.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/colResizable-1.3.min.js" type="text/javascript" ></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/dragtable/extend.dragtable.js" type="text/javascript" ></script>

<!--header menu needed-->
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/docs/docs.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/spectrum.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/listmenucolor/css/component.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/listmenucolor/css/default.css" media="screen" />
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/spectrum.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/docs/docs.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/docs/coloritems.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/docs/docs-title.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/spectrum/docs/docs-text.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/listmenucolor/modernizr.custom.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>magestore/pdfinvoiceplus/listmenucolor/jquery.dlmenu.js"></script>

<title><?php echo $this->__('Edit Design | Template %s', $this->getRequest()->getParam('id')) ?></title>