<?php
$displayOrderTable = Mage::getStoreConfig('tab1/order_information_system/display_order_table');
$displayProductImage = Mage::getStoreConfig('tab1/order_information_system/display_product_image');
$displayDiscount = Mage::getStoreConfig('tab1/order_information_system/display_discount');
$displayShippingRate = Mage::getStoreConfig('tab1/order_information_system/display_shipping_rates');
$displayTax = Mage::getStoreConfig('tab1/order_information_system/display_tax');
$displayCmsBlockAbove = Mage::getStoreConfig('tab1/cms_block_section/cms_block_above');
$cmsBlockIdAbove = Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_above');
$displayCmsBlockBelow = Mage::getStoreConfig('tab1/cms_block_section/cms_block_below');
$cmsBlockIdBelow = Mage::getStoreConfig('tab1/cms_block_section/cms_block_id_below');
$newsLetter = Mage::getStoreConfig('tab1/newsletter_subscription_section/display_section');
$_coreHelper = $this->helper('core');
$orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
$lastOrder = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
$shippingAddress = $lastOrder->getShippingAddress();
$point  = $orderObj->getRewardpointsEarn()
?>

<div class="thanks-wrapper">
    <div class="thanks-content">
        <div class="thanks-info">
            <div class="thanks-info-content">
                <div class="thank-title">
                    <h2><?php echo $this->__('เราได้รับคำสั่งซื้อของคุณแล้ว') ?></h2>
                    <p><?php echo $this->__('ขอบคุณสำหรับการเลือกซื้อสินค้ากับ CARNIVAL') ?></p>
                    <p>
                        <?php echo $this->__('หมายเลขคำสั่งซื้อของคุณ (ORDER NO.):') ?>
                        <strong>
                            <?php if ($this->getCanViewOrder()): ?>
                                <?php echo $this->__(sprintf('<a href="%s">%s</a>',
                                    $this->escapeHtml($this->getViewOrderUrl()),
                                    $this->escapeHtml($this->getOrderId()))) ?>
                            <?php else: ?>
                                <?php echo $this->__($this->escapeHtml($this->getOrderId())) ?>
                            <?php endif; ?>
                        </strong>
                    </p>
                </div>
                <div class="thanks-pay">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getTopBlock())->toHTML(); ?>
                </div>
                <div class="thanks-actions">
                <a class="button btn-continue btn-inline"
                   href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>"
                   title="<?php echo $this->__('เลือกซื้อสินค้าต่อ') ?>">
                    <?php echo $this->__('เลือกซื้อสินค้าต่อ') ?>
                </a>
                <?php if ($this->getCanViewOrder()): ?>
                    <?php echo $this->__(sprintf('<a class="button btn-view-order btn-inline" href="%s">%s</a>',
                        $this->escapeHtml($this->getViewOrderUrl()),
                        $this->escapeHtml('ดูรายละเอียดคำสั่งซื้อ'))) ?>
                <?php else: ?>
                    <a class="button btn-view-order btn-inline"><?php echo $this->escapeHtml('ดูรายละเอียดคำสั่งซื้อ'); ?>) ?></a>
                <?php endif; ?>
            </div>
            </div>
        </div>
        <div class="thanks-summary">
            <div class="thanks-summary-content">
                <div class="thanks-summary-title">
                    <h3><?php echo $this->__('สรุปคำสั่งซื้อ') ?></h3>
                </div>
                <div class="thk-delivery-address">
                    <h3><?php echo $this->__('ที่อยู่ในการจัดส่ง') ?></h3>
                    <?php if($this->getOrderId()): ?>
                        <p>
                            <span>
                                <?php echo $shippingAddress['street'] ? $shippingAddress['street'] : ''; ?>
                                <?php echo $shippingAddress['region'] ? ', '.$shippingAddress['region'] : ''; ?>
                                <?php echo $shippingAddress['city'] ?  ', '.$shippingAddress['city']: ''; ?>
                                <?php echo $shippingAddress['postcode'] ? ' '.$shippingAddress['postcode'] : ''; ?> </span></p>
                    <?php endif; ?>
                </div>
                <div class="thk-shipping-method">
                    <h3><?php echo $this->__('วิธีการจัดส่ง') ?></h3>
                    <p><?php echo $orderObj->getShippingDescription(); ?></p>
                </div>
                <div class="thk-product-list">
                    <h3><?php echo $this->__('รายการสินค้า') ?></h3>
                    <?php
                    //**********************************Order Details***************************
                    if ($displayOrderTable == 1):
                        if ($this->getOrderId()):
                            $orderItems = $orderObj->getAllVisibleItems();
                            ?>
                            <div class="products-summary">
                                <div class="products-summary-content">

                                    <?php foreach ($orderItems as $items) :
                                        $_product = Mage::getModel('catalog/product')->load($items->getProductId());
                                        $product_small_image_path = Mage::helper('catalog/image')->init($_product,
                                            'small_image')->resize(75);
                                        ?>
                                        <div class="product-item">
                                             <?php if ($displayProductImage == 1): ?>
                                                <div class="product-image">
                                                    <img src="<?php echo $product_small_image_path ?>" align="<?php echo $items->getName(); ?>"/>
                                                </div>
                                             <?php endif;?>
                                            <div class="product-info">
                                                <div class="product-name"><?php echo $items->getName(); ?></div>
                                                <div class="product-price">
                                                   <span><?php echo $_coreHelper->formatPrice($items->getPrice(),true) ?></span>
                                                </div>
                                                <div class="product-qty"><?php echo $this->__('จำนวน: ') ?><?php echo number_format($items->getQtyOrdered(), 0); ?></div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <div class="subtotal-content">
                                    <div class="sb-item subtotal">
                                        <span class="item-label"><?php echo $this->__('ราคาสินค้ารวม') ?></span>
                                        <span class="item-value"><?php echo $_coreHelper->formatPrice($orderObj->getSubtotal(), true) ?></span>
                                    </div>
                                    <?php if ($displayShippingRate == 1): ?>
                                        <div class="sb-item shipping">
                                            <span class="item-label"><?php echo $this->__('ค่าจัดส่ง') ?></span>
                                            <span class="item-value"><?php echo $_coreHelper->formatPrice($orderObj->getShippingInclTax(), true) ?></span>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($point > 0): ?>
                                        <div class="sb-item point">
                                            <span class="item-label"><?php echo $this->__('คะแนนสะสมได้รับ') ?></span>
                                            <span class="item-value"><?php echo '+'.$point; ?></span>
                                        </div>
                                    <?php endif; ?>

                                    <div class="sb-item grand_total">
                                        <span class="item-label"><strong><?php echo $this->__('รวมทั้งหมด	') ?></strong></span>
                                        <span class="item-value">
                                            <span class="subtotlal-value">
                                                <strong><?php echo $_coreHelper->formatPrice($orderObj->getGrandTotal(), true); ?></strong>
                                            </span>
                                        </span>
                                    </div>

                                </div>
                            </div>
                        <?php endif;
                    endif;
                    ?></div>
                </div>
            </div>
        </div>
    </div>

    <?php /* if ($this->getTopBlock() != false): ?>
        <?php if ($displayCmsBlockAbove == 1): ?>
            <div class="order-cms-block block1"><?php
            echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getTopBlock())->toHTML();
            ?></div><?php
        endif;
    endif;
    ?>


    <?php /* if ($this->getBottomBlock() != false): ?>
        <?php if ($displayCmsBlockBelow == 1): ?>
            <div class="order-cms-block block_2">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getBottomBlock())->toHTML(); ?>
            </div>
        <?php
        endif;
    endif;
    ?>

    <?php if ($newsLetter == 1): ?>
        <div class="order-newsletter">
        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
        </div><?php
    endif; */
    ?>
</div>
