<div class="totals">
	<!--body-->
    <?php $_totals = $this->getTotals('')?>
    <?php if ($_totals):?>
    <div class="body-total">
    <?php foreach ($_totals as $_code => $_total):?>
        <?php if ($_total->getBlockName()): ?>
            <?php if($_total->getCode() == 'tax'):?>
            <?php echo $this->getChildHtml('tax');?>
            <?php else:?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
            <?php endif;?>
        <?php else:?>
        <div class="<?php echo $_code?> totals-li">
            <div <?php echo $this->getLabelProperties()?> class="totals-label">
                <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
            </div>

            
            <div <?php echo $this->getValueProperties()?> class="totals-value">
                <?php echo Mage::helper('core')->currencyByStore($_total->getBaseValue(), $this->getOrder()->getStoreId()) ?>
            </div>
        </div>
        <?php endif?>
    <?php endforeach?>
    </div>
    <?php endif?>
	
	<!--footer-->
    <?php $_totals = $this->getTotals('footer')?>
    <?php if ($_totals):?>
    
    <div class="footer-total">
    <?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
        <?php if($_total->getValue()>0):?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <div class="<?php 
            if($_total->getCode()=='grand_total'){
                echo 'row-grandtotal';
            }else{
                echo $_code;
            } 
            ?> totals-li">
            <?php 
            if($_total->getCode() == 'grand_total') {
                $label_class = 'grand-label';
            }else{
                $label_class = 'totals-label';
            }
            ?>
            <div class="<?php echo $label_class; ?> totals-label" <?php echo $this->getLabelProperties()?>>
                <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
            </div>
            <?php 
            if($_total->getCode() == 'grand_total') {
                $value_class = 'grand-emph';
            }
            else{
                $value_class = 'emph-totals';
            }
            ?>
            <div <?php echo $this->getValueProperties()?> class="<?php echo $value_class; ?> totals-value">
                <strong class="<?php if($_total->getCode() == 'grand_total') echo 'grand_total';?>">
					<?php echo Mage::helper('core')->currencyByStore($_total->getBaseValue(), $this->getOrder()->getStoreId()) ?>
				</strong>
            </div>
        </div>
        <?php endif?>
        <?php endif?>
    <?php endforeach?>
    </div>
    <?php endif?> 
</div>

