<?php
$customerId = $this->getCustomerId();
?>
<div class="page-title">
    <h1><?php echo $this->__('My Credit Card') ?></h1>
    <a class="new-card" id="new-card" title="<?php echo $this->__('Add new credit/debit card')?>" onclick=""><?php echo $this->__('Add new credit/debit card')?></a>
</div>
<?php $_code= 'p2c2p' ?>
<form id="p2c2p-form" action="<?php echo $this->getUrl('p2c2p/Card/new') ?>" method="post" style="display: none">
    <h2 class="legend"><?php echo $this->__('Add new credit/debit card') ?></h2>
    <ul class="form-list p2c2p_new_card_form" id="card_form_2c2p_gateway">
        <li class="fields">
            <label for="<?php echo $_code ?>_cc_type_card"
                   class="required"><em>*</em><?php echo $this->__('Please select card type') ?></label>
            <div class="input-box">
                    <select autocomplete="off"
                            id="<?php echo $_code ?>_cc_type_card" name="card_type" class="required-entry">
                        <option value="credit_card"><?php echo $this->__('Credit Card') ?></option>
                        <option value="debit_card"><?php echo $this->__('Debit Card') ?></option>
                    </select>
            </div>
        </li>
        <li class="fields">
            <label for="<?php echo $_code ?>_cc_number"
                   class="required"><em>*</em><?php echo $this->__('Card number') ?></label>
            <div class="input-box">
                <input type="text" maxlength="16" autocomplete="off" data-encrypt="cardnumber"
                       class="input-text required-entry validate-cc-number validate-cc-type required"
                       id="<?php echo $_code ?>_cc_number"
                       title="<?php echo $this->__('Card number') ?>" value=""/>
            </div>
        </li>

        <li class="fields">
            <label for="<?php echo $_code ?>_cc_owner"
                   class="required"><em>*</em><?php echo $this->__('Cardholder Name'); ?>
            </label>
            <div class="input-box">
                <input type="text" name="holder_name" data-2c2p="holder_name" id="<?php echo $_code ?>_cc_name"
                       class="input-text required-entry"
                       title="<?php echo $this->__('Cardholder Name') ?>"
                />
            </div>
        </li>
        <li class="omise-sub-info">
            <ul>
                <li id="p2c2p_gateway_cc_type_exp_div" class="2c2p-exp-date">
                    <label for="<?php echo $_code ?>_expiration"
                           class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select class="input-text required-entry" data-encrypt="month" id="<?php echo $_code ?>_expiration">
                                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select class="input-text required-entry"  data-encrypt="year" id="<?php echo $_code ?>_expiration_yr">
                                <?php foreach ($this->getCcYears() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="fields" id="p2c2p_gateway_cc_type_cvv_div">
                    <label for="<?php echo $_code ?>_cc_cid"
                           class="required"><em>*</em><?php echo $this->__('CVV') ?></label>
                    <div class="input-box">
                        <div class="input-box">
                            <div class="v-fix">
                                <input autocomplete="off" data-encrypt="cvv"
                                       type="text"
                                       title="<?php echo $this->__('CVV') ?>"
                                       class="input-text cvv required-entry validate-cc-cvn"
                                       id="<?php echo $_code ?>_cc_cid"
                                       value=""/>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </li>

        <li>
            <div class="control">
                <input type="checkbox" value="1" name="payment[accept_term]" id="accept_term"
                       class="required-entry checkbox"/>
                <label for="accept_term"><?php echo $this->__('Accept Term & Condition') ?></label>
            </div>
        </li>

    </ul>

    <div class="buttons-set style1">
        <button type="button" id="close-p2c2p-form"
                class="button button-back btn-white">
            <span><span><?php echo $this->__('Back'); ?></span></span>
        </button>
        <button type="button" id="submit-p2c2p-form"
                class="button" onclick="validateAndSubmit()">
            <span><span><?php echo $this->__('Save'); ?></span></span>
        </button>
    </div>
</form>

<?php if ($customerId): ?>
    <?php $cardList = $this->getCardList($customerId) ?>
    <?php $defaultCard = $this->getDefaultCard($customerId); ?>


    <?php if($cardList->getSize()>0): ?>
        <table class="data-table" id="my-apps-table">
            <col width="" align="right" />
            <col width="" align="right" />
            <col width="1" align="right" />
            <thead>
            <tr>
                <th><?php echo $this->__('Card number') ?></th>
                <th><div><?php echo $this->__('Set as primary card') ?></div></th>
                <th><?php echo $this->__('Delete') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $cardNumber = array() ?>
            <?php foreach ($cardList  as $key => $value) :?>

                <tr>
                    <td>
                        <div class="wrapper_logo_card">
                            <?php if($value->getData('payment_scheme')=='VI')
                                    {
                                        $cardlogo ='images/icon-payment/logo-visa.png';
                                    }
                                    elseif ($value->getData('payment_scheme')=='MA') {
                                         $cardlogo ='images/icon-payment/logo-master.png';
                                     }
                                    elseif ($value->getData('payment_scheme')=='JC') {
                                         $cardlogo ='images/icon-payment/logo-jcb.png';
                                     }
                                     else
                                     {
                                        $cardlogo ='images/icon-payment/logo-visa.png';
                                     }  
                            ?>
                            <img  class="logo-card" src="<?php echo $this->getSkinUrl($cardlogo) ?> " alt="" >
                        </div>
                        <div class="wrapper_card_number">
                            <span class="cart-number"><?php echo $this->__($value->getData('masked_pan')) ?></span> <br/>
                        </div>
                    </td>
                    <td>
                        <input disabled="disabled" onclick="preventDefault(this)" type="checkbox" value="1" name="set_as_default" <?php if($defaultCard->getData('p2c2p_id') == $value->getData('p2c2p_id')): ?> checked<?php endif; ?> >
                        <label onclick="setDefaultCard('<?php echo  $value->getData('p2c2p_id') ?>')"><?php echo $this->__('set default') ?></label>
                    </td>
                    <td><a class="remove" href="#" onclick="removeCard('<?php echo  $value->getData('p2c2p_id') ?>')"><?php echo $this->__('x') ?></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="popup-delete-card" id="popup-delete-card" style="display: none" >
            <div class="popup-content">
                <span class="close-popup" id="popup-close-top"><?php echo $this->__('Close') ?></span>
                <h2><?php echo $this->__('Delete') ?></h2>
                <div class="text-content">
                    <?php echo $this->__('Are you sure you want to delete this credit card?') ?>
                </div>
                <div class="buttons-set style1">
                    <button type="button" id="popup-close"
                            class="button button-back btn-white">
                        <span><span><?php echo $this->__('Cancel'); ?></span></span>
                    </button>
                    <button type="button" id="delete-card-info" data-id-card="hehe"
                            class="button">
                        <span><span><?php echo $this->__('Delete'); ?></span></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="popup-delete-card" id="popup-update-card" style="display: none" >
            <div class="popup-content">
                <span class="close-popup" id="popup-close-top"><?php echo $this->__('Close') ?></span>
                <h2><?php echo $this->__('Set as primary card') ?></h2>
                <div class="text-content">
                    <?php echo $this->__('Are you sure you want to set this card as primary card?') ?>
                </div>
                <div class="buttons-set style1">
                    <button type="button" id="popup-close"
                            class="button button-back btn-white">
                        <span><span><?php echo $this->__('Cancel'); ?></span></span>
                    </button>
                    <button type="button" id="update_card_info" data-id-card="hehe"
                            class="button">
                        <span><span><?php echo $this->__('Are you sure? '); ?></span></span>
                    </button>
                </div>
            </div>
        </div>
    <?php else: ?>
        <p><?php echo $this->__('You have no saved cards.'); ?></p>
    <?php endif; ?>

    <div class="popup-already-save-card" id="popup-already-save-card"></div>



<?php endif; ?>
<?php         $test_mode = Mage::getStoreConfig('payment/p2c2p/gatewayurl', Mage::app()->getStore());
if($test_mode):
    ?>
    <script type="text/javascript" src="https://demo2.2c2p.com/2C2PFrontEnd/SecurePayment/api/my2c2p.1.6.9.min.js"></script>
<?php else: ?>
    <script type="text/javascript" src="https://t.2c2p.com/securepayment/api/my2c2p.1.6.9.min.js"></script>
<?php endif; ?>
<script type="text/javascript">
    //<![CDATA[
    var p2c2pForm = new VarienForm('p2c2p-form', true);
    //]]>
    function preventDefault(e) {
        e = e || window.event;
        if (e.preventDefault)
            e.preventDefault();
        e.returnValue = false;
    }

    jQuery('#popup-close, #popup-close-top').on('click', function () {
        $('popup-delete-card').hide();
        $('popup-update-card').hide();
    });

    jQuery('.new-card').on('click', function () {
        $('p2c2p-form').show();
    });

    jQuery('#close-p2c2p-form').on('click', function () {
        $('p2c2p-form').hide();
    });


    function removeCard(id) {
        $('popup-delete-card').show();
        jQuery('#delete-card-info').on('click', function () {
            var url = "<?php echo $this->getUrl('p2c2p/Card/remove');?>";
            jQuery.ajax({
                url: url ,
                type: "POST",
                data: {token: id},
                success: function(response){

                    if(response == "0"){
                        alert("Unable to remove your card. Please try again, and let us know if the problem persists.");
                        return;
                    }else
                    {
                        location.reload();
                    }
                }
            });


        });
    }
    function setDefaultCard(id) {
        $('popup-update-card').show();
        jQuery('#update_card_info').on('click', function () {
            var url = "<?php echo $this->getUrl('p2c2p/Card/setDefault');?>";
            jQuery.ajax({
                url: url ,
                type: "POST",
                data: {token: id},
                success: function(response){

                    if(response == "0"){
                        alert("Unable to remove your card. Please try again, and let us know if the problem persists.");
                        return;
                    }else
                    {
                        location.reload();
                    }
                }
            });


        });
    }

    function validateAndSubmit() {
        var p2c2pValidation = new Validation('p2c2p-form');
        if (p2c2pValidation.validate()) {

            My2c2p.getEncrypted("p2c2p-form",function(encryptedData,errCode,errDesc) {
                if(errCode!=0){ alert(errDesc+" ("+errCode+")"); }
                else {
                    var url ="<?php echo $this->getUrl('p2c2p/Card/new') ; ?>";

                    var request = new Ajax.Request(
                        url ,
                        {
                            type: "POST",
                            parameters: {
                                encryptedCardInfo: encryptedData.encryptedCardInfo,
                                maskedCardInfo: encryptedData.maskedCardInfo,
                                expMonthCardInfo: encryptedData.expMonthCardInfo,
                                expYearCardInfo: encryptedData.expYearCardInfo,
                                holder_name: jQuery('#p2c2p-form').find("input[name=holder_name]").val(),
                                card_type: jQuery('#p2c2p-form').find("select[name=card_type]").val()

                            },


                            onCreate: function () {
                                AmAjaxObj.showAnimation();
                            }.bind(this),

                            onComplete: function () {
                                AmAjaxObj.hideAnimation();
                            },

                            onSuccess: function (transport) {
                                // $('ruffle-card-info').hide();

                                try {
                                    JSON.parse(transport.responseText);
                                } catch (e) {

                                    if(transport.responseText ==="1" )
                                    {
                                        location.reload();

                                    }else
                                    {
                                        alert(transport.responseText);
                                        return false;
                                    }
                                }
                                var response = JSON.parse(transport.responseText);
                                if (response == 1)
                                {
                                    location.reload();
                                }
                                if (response.result) {

                                    $('popup-already-save-card').update(response.html_popup);

                                }
                            },
                        })


                }
            });


        }
    }
</script>
