<?php $column = $this->getColumn();
$_idx = $this->getId();
?>

<form id="advr-order-to-plain-<?php echo $_idx; ?>" action="<?php echo Mage::getModel('adminhtml/url')->getUrl('*/*/plain'); ?>" method="post">
    <input type="hidden" name="orders" value="<?php  echo $column->getOrders(); ?>"/>
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <a href="javascript:void(0);" onclick="document.getElementById('advr-order-to-plain-<?php echo $_idx; ?>').submit();">View orders</a>
</form>