<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Common
 */

/** @var $this Magpleasure_Common_Block_Template */
?>

<?php $_uid=$this->getData('uid'); ?>
<div id="mp_dialogs_<?php echo $_uid; ?>" class="mp-dialogs-container" ng-show="true"
     align="center">
    <div id="mp_modal_overlay" class="overlay_magento mp-overlay_modal"></div>
    <div id="dialog_contents_<?php echo $_uid; ?>" class="mp-dialog_contents" align="left">
        <?php echo $this->getChildHtml('magpleasure.dialogs.content.' . $_uid); ?>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[

    function verticalCenterDialog(name) {
        var contents = $('dialog_contents_' + name);
        var dialogs = $("mp_dialogs_" + name);

        if (contents && dialogs.style.display == 'block') {
            var block_height = contents.clientHeight;
            var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
            var block_top = (h - block_height) / 2;
            if (block_top < 0)
                block_top = 0;

            contents.style.top = block_top + 'px';
        }
    }

    if (window.addEventListener) {
        window.addEventListener('resize', function () {
            verticalCenterDialog('<?php echo $_uid; ?>');
        });
    } else {
        window.attachEvent('onResize', function () {
            verticalCenterDialog('<?php echo $_uid; ?>');
        });
    }

    function preventDefault(e) {
        e = e || window.event;
        if (e.preventDefault)
            e.preventDefault();
        e.returnValue = false;
    }

    $('mp_dialogs_<?php echo $_uid; ?>').onmousewheel  =
        function(event) {
            if (event && event.toElement.localName=='textarea'){
                /*to do disable position*/
            }else{
                event.preventDefault();
            }
        };

    // ]]>
</script>