<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<!--<div id="mastercheckout-forgot">-->
<form action="#" id="form-validate" onsubmit="return false;">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
<!--        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>-->
        <button id="mastercheckout-submit" onclick="forgotPasswordCode(this)" type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
<!--        <input id="mastercheckout-submit" type="submit" title="<?php echo $this->__('Submit') ?>" class="button" value="<?php echo $this->__('Submit') ?>" name="ggg"/>-->
    </div>
</form>
<!--</div>-->
<script type="text/javascript">
//<![CDATA[
    var forgotForm = new VarienForm('form-validate', true);
//    var forgotForm = new VarienForm('login-form', true);
    $('email_address').observe('keypress', bindLoginPost);
//    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            console.log("aaaaaaaaaaaaaa");
            forgotPost();
            forgotForm.submit();
        }
    }
    function forgotPasswordCode(button)
    {
        if(forgotForm.validator && forgotForm.validator.validate()){
            console.log("bbbbbbbbbbbb");
            forgotPost();
            button.disabled = true;
//            forgotForm.submit();
            return false;
        }
        return false;
    }

    function forgotPost(){
        var url = "<?php echo $this->getUrl('customer/account/forgotpasswordpost',array('_secure'=>true))?>";
        var email = jQuery("#email_address").val();
//        var validator = new Validation(this.form);
//        console.log(validator);
//        if (validator.validate()) {}
        var request = new Ajax.Request(
            url,
            {method: 'post', parameters: {email:email},
            onComplete: function(transport) {
                    if (200 == transport.status){
                        disablePopup('forgot-password-content');
                    }
              }
            }
        );
    }
//]]>
</script>
