<?php
$Imagehome_grid = 0;
$id = $this->getRequest()->getParam('id');
/** @var Magebuzz_Imagehome_Helper_Data $imageHomeHelper **/
$imageHomeHelper = Mage::helper('imagehome');
$Imagehomes = $imageHomeHelper->getImagehome($id);
if ($Imagehomes->getImagehomeGrid()) {
    $Imagehome_grid = $Imagehomes->getImagehomeGrid();
//    $Imagehome_grid=$imageHomeHelper->processCutomBlock($Imagehome_grid);
}
$categoriesSelected = $imageHomeHelper->getCategoriesOptions();
$bannerSelecteds=$imageHomeHelper->getBannerOptions();

?>

<div class="container-fluid content-header">
    <div class="icon-head head-adminhtml-imagehome">
        <button style="display: none" data-bind="click: addNewWidget" id="newwidget">Add new widget</button>
        <button  style="display: none" data-bind="click: save" id="savewidget">Save widget</button>
    </div>
    <br>
    <div data-bind="component: {name: 'dashboard-grid_', params: $data}"></div>
</div>

<style type="text/css">
    .grid-stack {
        background: lightgoldenrodyellow;
    }

    .grid-stack-item-content {
        color: #2c3e50;
        text-align: center;
        border: #18bc9c 1px solid;
    }
</style>
<script type="text/javascript">

    var $jqs = jQuery.noConflict();

    ko.components.register('dashboard-grid_', {
        viewModel: {
            createViewModel: function (controller, componentInfo) {
                var ViewModel = function (controller, componentInfo) {
                    var grid = null;

                    this.widgets = controller.widgets;

                    this.afterAddWidget = function (items) {
                        if (grid == null) {
                            grid = $jqs(componentInfo.element).find('.grid-stack').gridstack({
                                auto: false
                            }).data('gridstack');
                        }

                        var item = _.find(items, function (i) {
                            return i.nodeType == 1
                        });
                        grid.addWidget(item);
                        ko.utils.domNodeDisposal.addDisposeCallback(item, function () {
                            grid.removeWidget(item);
                        });
                        jQuery('select.custom-image').each(function () {
                            if(jQuery(this).attr('value'))
                            {
                                jQuery(this).find('option[value="'+jQuery(this).attr('value')+'"]').attr('selected',true);
                            }
                        });

                    };
                };

                return new ViewModel(controller, componentInfo);
            }
        },
        template: {element: 'gridstack-template'}
    });

    $jqs(function () {
        var Controller = function (widgets) {
            var self = this;
            this.widgets = ko.observableArray(widgets);
            this.addNewWidget = function () {
                //alert(ko.utils.stringifyJson(self.widgets));
                var obj = ko.utils.stringifyJson(this.widgets()[widgets.length - 1]['index']);
                var currentBigestIndex=0;
                ////check beacause custom is on top
                for(var i = 0; i < widgets.length; i++)
                {
                    var dataIndex=parseInt(ko.utils.stringifyJson(this.widgets()[i]['index']))
                    if(currentBigestIndex < dataIndex)
                    {
                        currentBigestIndex= dataIndex;
                    }
                }
                var index = currentBigestIndex + 1;
                this.widgets.push({
                    x: 0,
                    y: 0,
                    width: Math.floor(1 + 3 * Math.random()),
                    height: Math.floor(1 + 3 * Math.random()),
                    index: index,
                    category_name_attr : 'category_id[' + index + ']',
                    category_title_name_attr: 'category_title[' + index +']',
                    category_url_name_attr: 'category_url[' + index +']',
                    banner_name_attr : 'banner_id[' + index + ']',
                    banner_title_name_attr: 'banner_title[' + index +']',
                    banner_url_name_attr: 'banner_url[' + index +']',
                    auto_position: true
                });
                return false;
            };
            this.deleteWidget = function (item) {
                self.widgets.remove(item);
                return false;
            };
            self.save = function (item) {



                var obj = this.widgets();


                this.widgets = _.map($jqs('.grid-stack > .grid-stack-item:visible'), function (el) {
                    el = $jqs(el);
                    var node = el.data('_gridstack_node');

                    return {
                        id: el.attr('data-custom-id'),
                        x: node.x,
                        y: node.y,
                        width: node.width,
                        height: node.height,
                    };
                }, this)
                var imagegrif = [];
                for (var i = 0; i < widgets.length; i++) {
                    var str = ko.utils.stringifyJson(self.widgets[i]);
                    var j = ko.utils.stringifyJson(obj[i]['index'])
                    var grid = str.replace('}', ',"index" :' + j + '}');

                    imagegrif.push(grid);
                }
                $('imagehome_grid').value = imagegrif;
            };
        };
        if (<?php echo $Imagehome_grid ?> == 0) {
            var widgets = [
                {x: 0, y: 0, width: 2, height: 2, image: 'Desert.jpg', index: 1},
                {x: 2, y: 0, width: 4, height: 2, image: 'Desert.jpg', index: 2},
                {x: 6, y: 0, width: 2, height: 4, image: 'Desert.jpg', index: 3},
                {x: 1, y: 2, width: 4, height: 2, image: 'Desert.jpg', index: 4}
            ];
        } else {
            var widgets = <?php echo $Imagehome_grid ?>;
        }



        var controller = new Controller(widgets);
        ko.applyBindings(controller);
    });


    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                input.next().src = e.target.result;
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    $j('magebuzz_mage').value = "['Saab', 'Volvo', 'BMW']";
</script>

<template id="gridstack-template">
    <div class="grid-stack" data-bind="foreach: {data: widgets, afterRender: afterAddWidget}">
        <div class="grid-stack-item" data-bind="attr: {'data-gs-x': $data.x, 'data-gs-y': $data.y, 'data-gs-width': $data.width, 'data-gs-height': $data.height, 'data-gs-auto-position': $data.auto_position , 'data-index' : $data.index} ">
            <div class="grid-stack-item-content">
                <button data-bind="click: $root.deleteWidget" style="float: right;background: none;border: none !important;">
                    <img id="aw_popup_close_btn"  src="http://carnivalbkk.mgfdev.com/skin/frontend/carnival/default/popup/images/close_label.gif">
                </button>
                <input type='file'  data="magebuzz_mage" name="magebuzz_mage[]" id="magebuzz-image" onchange="readURL(this);" />
                <img   data-bind=" attr: { 'src': '<?php echo Mage::getBaseUrl('media'); ?>magebuzz\/' + $data.image  }"  style="width: 100%;height: 100%;position: absolute;z-index: -10;margin: 0;padding: 0;left: 0;top: 0;" src="" alt="your image" />
                <textarea  data-bind='text: $data.html' id="magebuzz_html"  name="magebuzz_html[]" style="float: left;width: 100%;" placeholder="html"></textarea>
                <select data-bind="
                            selectedOptions : ($data.category) ? '1' : '0'
                        "
                        onchange="displayProducts(this)" >
                    <option value="0"><?php echo $imageHomeHelper->__('No') ?></option>
                    <option value="1"><?php echo $imageHomeHelper->__('Yes') ?></option>
                </select>
                <select data-bind="
                            visible : ($data.category) ? true : false,
                            selectedOptions : $data.category,
                            attr: {
                                'name' : $data.category_name_attr,
                                'value' : $data.category,
                                'id' : $data.category_name_attr
                            }
                        "
                        class="custom-image"
                        value=""
                        style="display: none">
                    <option value=""><?php echo $imageHomeHelper->__('Please select category') ?></option>
                    <option value="<?php echo $categoriesSelected->getId() ?>"><?php echo $categoriesSelected->getName() ?></option>
                </select>
                <input type='text'
                       data-bind="
                            visible : ($data.category) ? true : false,
                                 attr: {
                                'name' : $data.category_title_name_attr,
                                'value' : $data.category_title
                            }
                        "
                        placeholder="title" />
                <input type='text'
                       data-bind="
                            visible : ($data.category) ? true : false,
                                       attr: {
                                'name' : $data.category_url_name_attr,
                                'value' : $data.category_url
                            }
                        "
                      placeholder="url" />

                <select data-bind="
                            selectedOptions : ($data.banner) ? '1' : '0'
                        "
                        onchange="displayBanner(this)" >
                    <option value="0"><?php echo $imageHomeHelper->__('No') ?></option>
                    <option value="1"><?php echo $imageHomeHelper->__('Yes') ?></option>
                </select>
                <select data-bind="
                            visible : ($data.banner) ? true : false,
                            selectedOptions : $data.banner,
                            attr: {
                                'name' : $data.banner_name_attr,
                                'value' : $data.banner,
                                'id' : $data.banner_name_attr
                            }
                        "
                        class="custom-image"
                        value=""
                        style="display: none">
                    <option value=""><?php echo $imageHomeHelper->__('Please select Banner') ?></option>
                    <?php foreach ($bannerSelecteds as $bannerSelected): ?>
                    <option value="<?php echo $bannerSelected->getData('block_id') ?>"><?php echo $bannerSelected->getData('block_title') ?></option>
                    <?php endforeach; ?>
                </select>
                <input type='text'
                       data-bind="
                            visible : ($data.banner) ? true : false,
                                 attr: {
                                'name' : $data.banner_title_name_attr,
                                'value' : $data.banner_title
                            }
                        "
                       placeholder="banner title" />
                <input type='text'
                       data-bind="
                            visible : ($data.banner) ? true : false,
                                       attr: {
                                'name' : $data.banner_url_name_attr,
                                'value' : $data.banner_url
                            }
                        "
                       placeholder="banner url" />



            </div>
        </div></div><!-- <---- NO SPACE BETWEEN THESE CLOSING TAGS -->
</template>

<input type="hidden"  name="imagehome_grid" id="imagehome_grid" width="100%" />
<script>
    function displayProducts(element) {
        if(jQuery(element).val() == 1) {
            jQuery(element).next().show();
            jQuery(element).next().next().show();
            jQuery(element).next().next().next().show();
        }

    else {
            jQuery(element).next().val('');
            jQuery(element).next().hide();
            jQuery(element).next().next().val('');
            jQuery(element).next().next().hide();
            jQuery(element).next().next().next().val('');
            jQuery(element).next().next().next().hide();
        }
    }

    function displayBanner(element) {
        if(jQuery(element).val() == 1) {
            jQuery(element).next().show();
            jQuery(element).next().next().show();
            jQuery(element).next().next().next().show();
        }

        else {
            jQuery(element).next().val('');
            jQuery(element).next().hide();
            jQuery(element).next().next().val('');
            jQuery(element).next().next().hide();
            jQuery(element).next().next().next().val('');
            jQuery(element).next().next().next().hide();
        }
    }




</script>