<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Ajaxlogin
 */
?>
<div class="am-login-forgotpassword">
    <form method="post" id="amajaxlogin-form-validate">
            <div class="am-login-forgotpassword-form-list">
                <ul class="form-list">
                    <li>
                        <!-- <label for="email_address" class="required"><em>*</em><?php //echo $this->__('Email Address') ?></label> -->
                        <div class="input-box">
                            <input type="text" name="email" alt="email" id="email_address" placeholder="<?php echo $this->__('Enter your email') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = '<?php echo $this->__('Enter your email') ?>'" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                        </div>
                    </li>
                </ul>
              <div class="button am-login-button" onclick="AmAjaxLoginObj.forgotPasswordSend();"><span><span><?php echo $this->__('Submit') ?></span></span></div>
            </div>
            <!-- <p class="required"><?php //echo $this->__('* Required Fields') ?></p> -->

    </form>
</div>
