<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
/** @var Magpleasure_Blog_Block_Comments_Message $this */
?>
<div class="mpblog-comment" id="mp-blog-comment-<?php echo $this->getMessageId(); ?>"<?php if ($this->getIsAjax()): ?> style="display: none;"<?php endif; ?>>
    <?php if ($this->isReply()): ?>
    <div class="is-reply"></div>
    <?php endif; ?>
    <div class="mp-comment-content <?php if ($this->isMyComment()): ?>my-comment<?php endif; ?>">
        <div class="mp-comment-header fix-me">
            <span class="mp-comment-author">
                <strong><?php echo $this->escapeHtml($this->getAuthor()); ?></strong>
            </span>
            <span class="mp-comment-date">
                <?php echo $this->__("%s at %s", $this->getDate(), $this->getTime()); ?>
            </span>
            <?php if ($this->getNeedApproveMessage()): ?>
                <span class="mp-comment-willapprove"><?php echo $this->__("This comment will become public after administrator approval."); ?></span>
            <?php endif; ?>
        </div>
        <?php echo $this->getContent(); ?>
        <div class="form-actions">
            <span class="mp-comment-reply-btn"><a href="#mp-comment-form-<?php echo $this->getMessageId(); ?>" onclick="blogComments.getForm('mp-comment-form-<?php echo $this->getMessageId(); ?>', <?php echo $this->getMessageId(); ?>); return false;"><?php echo $this->__("Reply"); ?></a></span>
        </div>
    </div>
    <div class="mp-replies">
        <?php echo $this->getRepliesHtml(); ?>
        <div class="mp-comment-form" id="mp-comment-form-<?php echo $this->getMessageId(); ?>" style="display: none;"></div>
    </div>
</div>
