<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Content_Post_Details $this  */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();

/** @var Magpleasure_Blog_Model_Post $post  */
$post = $this->getPost();
?>

<?php if ($helper->getUseTags()): ?>
    <?php echo $this->getTagsHtml(); ?>
<?php endif; ?>
<?php if ($helper->getUseCategories()): ?>
    <?php echo $this->getCategoriesHtml(); ?>
<?php endif; ?>