<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<?php echo $this->getChildHtml('mpblog_post_tabs'); ?>
<?php echo $this->getFormHtml() ?>

<script type="text/javascript">
    editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
</script>
<?php echo $this->getFormScripts() ?>
