<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php if ($this->getButtonsCount()): ?>
<div class="mpblog-social-container" id="social">
    <div class="mp-buttons fix-me">
        <label><?php echo $this->__('share') ?></label>
        <ul>
        <?php foreach($this->getButtons() as $button): ?>

            <?php if ($this->getHasImage($button)): ?>
            <li>
                <?php if ($button->getIsTemplate()): ?>
                    <?php echo $this->getButtonHtml($button); ?>
                <?php else: ?>
                    <a target="_blank" href="<?php echo $this->getButtonUrl($button); ?>" title="<?php echo $button->getLabel(); ?>">
                        <i class="blog-icon <?php echo $button->getValue(); ?>"></i>
                    </a>
                <?php endif; ?>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
