<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php /** @var Magpleasure_Blog_Block_Adminhtml_System_Config_Field_Layout_Renderer $this */ ?>

<div class="mp-layout-element"
     mp-name="<?php echo $this->getElementName(); ?>"
     mp-id="<?php echo $this->getElementId(); ?>"
     mp-value='<?php echo $this->getElementValue() ?>'
     mp-config='<?php echo $this->getLayoutConfigJson(); ?>'>

</div>

