<?php
$Imagehome_grid = 0;

$Imagehomes = Mage::helper('imagehome')->getImagehomes();

if ($Imagehomes->getImagehomeGrid()) {
    $Imagehome_grid = $Imagehomes->getImagehomeGrid();
}
?>

<style type="text/css">
    .grid-stack {
        background: lightgoldenrodyellow;
    }

    .grid-stack-item-content {
        color: #2c3e50;
        text-align: center;
        background-color: #18bc9c;
    }


</style>
<div class="container-fluid">
    <div data-bind="component: {name: 'dashboard-grid_', params: $data}"></div>
</div>
<template id="gridstack-template">
    <div class="grid-stack" data-bind="foreach: {data: widgets, afterRender: afterAddWidget}">
        <div class="grid-stack-item" data-bind="attr: {'data-gs-x': $data.x, 'data-gs-y': $data.y, 'data-gs-width': $data.width, 'data-gs-height': $data.height, 'data-gs-auto-position': $data.auto_position , 'data-index' : $data.index} ">
            <div class="grid-stack-item-content home-img" data-bind=" attr: { 'style': 'background-image:' + 'url(<?php echo Mage::getBaseUrl('media'); ?>magebuzz\/' + $data.image + ')' }" style="">
                <img  data-bind=" attr: { 'src': '<?php echo Mage::getBaseUrl('media'); ?>magebuzz\/' + $data.image  }"  style="width: 100%; height: 100%;position: absolute;z-index: -10;margin: 0;padding: 0;left: 0;top: 0;" src="" alt="your image" />
                <textarea hidden="true"  data-bind='text: $data.html' id="magebuzz_html"  name="magebuzz_html[]" style="float: left;width: 100%;" placeholder="html"></textarea>

                <div id="magebuzz_htmlgrid">

                </div>
            </div>
        </div>
    </div><!-- <---- NO SPACE BETWEEN THESE CLOSING TAGS -->
</template>
<script type="text/javascript">
    var $jqs = jQuery.noConflict();

    ko.components.register('dashboard-grid_', {
        viewModel: {
            createViewModel: function (controller, componentInfo) {
                var ViewModel = function (controller, componentInfo) {
                    var grid = null;

                    this.widgets = controller.widgets;

                    this.afterAddWidget = function (items) {
                        if (grid == null) {
                            grid = $jqs(componentInfo.element).find('.grid-stack').gridstack({
                                auto: false

                            }).data('gridstack');
                        }
                        $('magebuzz_htmlgrid').innerHTML = $('magebuzz_html').value;
                        var firstChild = $('magebuzz_htmlgrid').children[0];
                        if(firstChild.getAttribute('href')){
                          var url = firstChild.getAttribute('href');
                          var parentElm = $('magebuzz_htmlgrid').parentNode;
                          var firstImge = parentElm.children[0];
                          firstImge.onclick = function() {
                            window.location.href = url;
                          };
                          firstImge.style.cursor = 'pointer';
                        }
                        var item = _.find(items, function (i) {
                            return i.nodeType == 1
                        });
                        grid.addWidget(item);
                        ko.utils.domNodeDisposal.addDisposeCallback(item, function () {
                            grid.removeWidget(item);
                        });
                    };
                };

                return new ViewModel(controller, componentInfo);
            }
        },
        template: {element: 'gridstack-template'}
    });

    $jqs(function () {
        var Controller = function (widgets) {
            var self = this;
            this.widgets = ko.observableArray(widgets);

        };
        if (<?php echo $Imagehome_grid ?> == 0) {
            var widgets = [
                {x: 0, y: 0, width: 2, height: 2, image: 'Desert.jpg', index: 1},
                {x: 2, y: 0, width: 4, height: 2, image: 'Desert.jpg', index: 2},
                {x: 6, y: 0, width: 2, height: 4, image: 'Desert.jpg', index: 3},
                {x: 1, y: 2, width: 4, height: 2, image: 'Desert.jpg', index: 4}
            ];
        } else {
            var widgets = <?php echo $Imagehome_grid ?>;
        }

        var controller = new Controller(widgets);
        ko.applyBindings(controller);
    });



</script>
