<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>

<g:plusone recommendations="false" count="false" annotation="none"></g:plusone>
<script type="text/javascript">
    //<![CDATA[

    window.___gcfg = {
        lang: '<?php echo $this->getLocaleCode(); ?>'
    };

    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();

    //]]>
</script>
