<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
/** @var Magpleasure_Blog_Block_Social_Wrapper $this */
?>

<!-- Twitter Card data -->
<?php if ($this->hasThumbnail()): ?>
    <meta name="twitter:card" content="summary_large_image" />
    <?php else: ?>
    <meta name="twitter:card" content="summary" />
<?php endif; ?>
<?php if ($this->getPublisherTwitter()): ?>
    <meta name="twitter:site" content="<?php echo $this->getPublisherTwitter(); ?>" />
<?php endif; ?>
<meta name="twitter:title" content="<?php echo $this->getPostTitle(); ?>" />
<meta name="twitter:description" content="<?php echo $this->getPostMetaDescription(); ?>" />
<?php if ($this->getAuthorTwitter()): ?>
    <meta name="twitter:creator" content="<?php echo $this->getAuthorTwitter(); ?>" />
<?php endif; ?>
<meta name="twitter:image:src" content="<?php echo $this->getPostUrl(); ?>" />

<!-- Open Graph data -->
<meta property="og:title" content="<?php echo $this->getPostTitle();?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $this->getPostUrl(); ?>" />
<?php if ($this->hasThumbnail()): ?>
    <meta property="og:image" content="<?php echo $this->getThumbnailSrc(); ?>" />
<?php endif; ?>
<meta property="og:description" content="<?php echo $this->getPostMetaDescription(); ?>" />
<meta property="og:site_name" content="<?php echo $this->getSiteName(); ?>" />
<?php if ($this->getPublisherFacebook()): ?>
    <meta property="article:publisher" content="<?php echo $this->getPublisherFacebook(); ?>" />
<?php endif; ?>
<?php if ($this->getAuthorFacebook()): ?>
    <meta property="article:author" content="<?php echo $this->getAuthorFacebook(); ?>" />
<?php endif; ?>
<meta property="article:published_time" content="<?php echo $this->getPostModifiedDate(); ?>" />
<meta property="article:modified_time" content="<?php echo $this->getPostPublishedDate(); ?>" />
<meta property="article:section" content="<?php echo $this->getPostCategories(); ?>" />
<?php if ($this->getPostTags()->getSize()): ?>
    <?php foreach ($this->getPostTags() as $tag): ?>
        <meta property="article:tag" content="<?php echo $this->escapeHtml($tag->getName()); ?>" />
    <?php endforeach; ?>
<?php endif; ?>

<!-- Google Search Robot -->
<meta itemprop="name" content="<?php echo $this->getPostTitle(); ?>">
<meta itemprop="description" content="<?php echo $this->getPostMetaDescription(); ?>">
<?php if ($this->hasThumbnail()): ?>
    <meta itemprop="image" content="<?php echo $this->getThumbnailSrc(); ?>">
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[

    $$('html').each(function(element){
        $(element).setAttribute('itemtype','http://schema.org/Blog');
        $(element).setAttribute('itemscope', "");
    });

    //]]>
</script>

