<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Customerattr
 */
?>
<?php /* @var $this Amasty_Customerattr_Block_Adminhtml_Customer_Reports_Edit_Tab_Main */ ?>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper(
            'amcustomerattr'
        )->__('Reports'); ?></h4>
</div>
<div class="fieldset">
    <?php if ($this->showReports()): ?>
        <?php if (count($this->getAttributeValues())): ?>
            <div id="chartdiv" style="width: 700px; height: 500px;"></div>
            <script type="text/javascript">
                $('product_attribute_tabs_main_content').show();

                jQuery(document).ready(function () {
                    var data = [
                        <?php foreach ($this->getAttributeValues() as $attrId => $values): ?>
                        ['<?php echo $values['label']?>', <?php echo $values['qty']?>],
                        <?php endforeach;?>
                    ];
                    var plot1 = jQuery.jqplot('chartdiv', [data],
                        {
                            seriesDefaults: {
                                // Make this a pie chart.
                                renderer: jQuery.jqplot.PieRenderer,
                                rendererOptions: {
                                    // Put data labels on the pie slices.
                                    // By default, labels show the percentage of the slice.
                                    showDataLabels: true,
                                    dataLabels: 'decimal'
                                }
                            },
                            legend: {show: true, location: 'e'}
                        }
                    );
                });
            <?php else: ?>
                <?php echo $this->__(
                    'Looks like nobody has placed any data yet or there is no options for this attribute'
                ); ?>
            <?php endif ?>
        </script>
    <?php else: ?>
        <?php echo $this->__(
            'Usage reports with visual graphs are available for attributes: checkboxes, multiple select, drop-downs, radio buttons'
        ); ?>
    <?php endif ?>

</div>