<?php

/*

Plumrocket Inc.

NOTICE OF LICENSE

This source file is subject to the End-user License Agreement
that is available through the world-wide-web at this URL:
http://wiki.plumrocket.net/wiki/EULA
If you are unable to obtain it through the world-wide-web, please
send an email to support@plumrocket.com so we can send you a copy immediately.

@package    Plumrocket_Cart_Reservation-v1.5.x
@copyright  Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
@license    http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 
*/
?>
<?php if ($this->modeReserveCart()) { ?>
    <div class="cart-reservation">
        <div>
            <div class="title">
                <p><?php echo $this->__('Time') ?></p>
                <p><?php echo $this->__('remaining') ?></p>
            </div>
            <div class="clockpopup"></div>
        </div>
    </div>
    <script type="text/javascript">
        var clockpopup;
        var time = <?php echo $this->getTime(); ?>;
        $j(document).ready(function () {
            if (time > 0) {

                var clockpopup;
                clockpopup = $j('.clockpopup').FlipClock({
                    clockFace: 'DailyCounter',
                    autoStart: false,
                    callbacks: {
                        stop: function () {
                            location.reload();
                        }
                    }
                });
                clockpopup.setTime(time);
                clockpopup.setCountdown(true);
                clockpopup.start();
            }
        });
    </script>
<?php } ?>