<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_SeoRichData
 */
?>
<div itemscope="" itemtype="https://schema.org/Organization">
    <meta itemprop="name" content="<?php echo Mage::getStoreConfig('design/header/logo_alt') ?>" />
    <meta itemprop="url" content="<?php echo $this->getUrl('') ?>" />
    <meta itemprop="logo" content="<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')) ?>" />
</div>