<?php

/*

Plumrocket Inc.

NOTICE OF LICENSE

This source file is subject to the End-user License Agreement
that is available through the world-wide-web at this URL:
http://wiki.plumrocket.net/wiki/EULA
If you are unable to obtain it through the world-wide-web, please
send an email to support@plumrocket.com so we can send you a copy immediately.

@package    Plumrocket_Cart_Reservation-v1.5.x
@copyright  Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
@license    http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 
*/
?>

<p class="cr-product-timer">
	<span class="cntdown-product" data-noempty="1"></span>
	<span class="cntdown-source" style="display: none;"><?php echo $this->getTime(); ?></span>
	<span class="cntdown-ctime" style="display: none;"><?php echo time() ?></span>
</p>