<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Common
 */

?>

<div class="mp-dialog-overlay" id="mp-dialog-overlay" style="display: none;"></div>
<div class="mp-dialog-loader" id="mp-dialog-loader" style="display: none;">
    <div class="mp-dialog-loader-wrapper">
        <div class="mp-dialog-loader-container">
            <div class="ajax-loager"></div>
            <div class="loader-message"><span><?php echo $this->__("Loading..."); ?></span></div>
        </div>
    </div>
</div>