<?php
$templateObject = $this->getDataObject();
$logo = $templateObject->getData('company_logo');
//change by Jack 19/01/2015
$logoUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/logo/' . $logo ;
$logoUrlConverter = Mage::helper('pdfinvoiceplus/product')->convertImage($logoUrl);
//
$name = $templateObject->getData('company_name');
$address = $templateObject->getData('company_address');
$phone = $templateObject->getData('company_telephone');
$email = $templateObject->getData('company_email');
$fax = $templateObject->getData('company_fax');
$businessId = $templateObject->getData('business_id');
$vatnumber = $templateObject->getData('vat_number');
$vatoffice = $templateObject->getData('vat_office');
$note = $templateObject->getData('note');
$footer = $templateObject->getData('footer');
$footerHeight = $templateObject->getFooterHeight();
$color = 'CC0000';
$pageFormat = $templateObject->getFormat();
$barcode_invoice = $templateObject->getBarcodeInvoice();
$display_images = $templateObject->getDisplayImages();
$orientation = $templateObject->getOrientation();
$font_size_2 = '12pt';
if ($orientation == 0) {
    if ($pageFormat == 'A5') {
        $title_width = '83%';
        $font_size_2 = '11pt';
    } else {
        $title_width = '90%';
    }
} elseif ($orientation == 1) {
    if ($pageFormat == 'A5') {
        $title_width = '88.5%';
    } else {
        $title_width = '93%';
    }
}
$barcode = $templateObject->getBarcode();
$barcode_type = $templateObject->getBarcodeType();
//$barcode_value = Mage::helper('pdfinvoiceplus/pdf')->getBarcodeValue();
$term = $templateObject->getTermsConditions();
$status = $templateObject->getStatus();
?>
<head>
    <style>
        *{margin: 0; padding: 0;}
        body {
            font-size: 14px;
            max-width:100%;
            margin: 0 auto;
            font-family: "Ubuntu Regular", "Ubuntu Light", arial;		
            font-size-adjust: none;
            width: 100%;
        }
        /*reset*/
        .template04 div, p, span, th, td {
            word-wrap: break-word;
            word-break: break-all;
        }

        .template04 td { vertical-align: top; }

        .template04 .items td.blanktotal {
            background-color: #FFFFFF;
            border: 0mm none #fff;
            border-top: 0.1mm solid #fff;
            border-right: 0.1mm solid #fff;
        }

        .template04 .top-title span {
            display: block;
            font-size: 15px;
            color: #000;
        }
        .template04 .table-data tbody td.label{
            color: #2f2f2f;
            font-family: 'Ubuntu';
            font-weight: bold;
            font-size: 16px;
        }
        .template04 .table-data thead tr{
            border-bottom: 6px solid;
            border-color: #<?php echo $color ?>;
            height: 50px;
        }

        /* New Style for invoice 05 */
        /* Header style*/
        .template04 .myheader-iv{
            width: 95%;
            margin-right: 5%;		
            position: relative;		
            float: left;	

            clear: both;
        }
        .template04 .top-header-iv{
            clear: both;
            width: 100%;
            float: left;
        }
        .template04 .bottom-header-iv{
            clear: both;
            width: 100%;
            float: left;    
            margin-top:10px;
        }

        .template04 .title-page-iv1{
            float: left;
            width: 75%;
            /*            padding: 0px 0px 0px 4%;
                        background-color: #cc0000;*/
        }
        .template04 .title-page-iv1 .order1{
            font-family: 'Ubuntu Regular';
            color: #FFFFFF;
            text-align: left;
            font-size: 25px;
            line-height: 50px;
            font-weight: normal;
            text-transform: uppercase;
            background-color: #cc0000;
            width: 50%;
            padding-left: 5.334%;
        }
        .template04 .barcode {
            margin-top: 5px;
            margin-bottom: 5px;
            float: left;
            text-align: left;
            margin-left: 5.334%;
        }
        
       /*      Zeus 28/01 */   
 <?php 
    
    if($barcode_type == 'QR' && $barcode == 1){
        ?>
   
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/QR.jpg'; ?>") no-repeat;
    }
     <?php
    }
   ?>
    <?php
    if($barcode_type == 'IMB' || $barcode_type == 'RM4SCC' || $barcode_type == 'KIX' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/IMB.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    <?php
    if($barcode_type == 'UPCA' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/UPCA.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN8' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN8.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN128A' || $barcode_type == 'C93' || $barcode_type == 'MSI' || $barcode_type == 'CODABAR' || $barcode_type == 'CODE11' || $barcode_type == 'C39' || $barcode_type == 'S25' || $barcode_type == 'C128A'  && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN128A.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN13' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN13.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'POSTNET' || $barcode_type == 'PLANET' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/POSTNET.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    /*      Zeus 28/01 */     

        .template04 .logo-iv{
            width:30%;							
            text-align: right; 
            float: right;
        }

        .template04 .id-invoice-iv{
            text-align: left;
            width:45%;
            float:left;
            margin-left: 4%;
            /*margin-top: 60px;*/
        }
        .template04 .info-iv{
            width:50%; 
            color:#000;
            font-size: 15px;
            text-align: right; 
            float: right;
        }

        /*  Main style */
        .template04 .main-content{				
            clear: both;
            margin: 0 3.6% 0 3.6%;
            max-width: 92.8%;
        }


        .template04 .info-cus{
            float: left;
            width: 100%;
        }
        .template04 .payment-box,
        .template04 .billing-box{
            width: 49%;
            float: left;				
        }

        .template04 .shipping-box,
        .template04 .shipping-add-box{
            float: right;
            width: 49%;				
        }
        .template04 .title-label{
            color: <?php echo '#' . $color; ?>;
            font-family: 'Ubuntu';
            font-size: 14px;
            font-weight: bold;
            text-transform: uppercase;
            padding: 0 20px;
        }
        .template04 .shipping-box .content,
        .template04 .shipping-add-box .content,
        .template04 .payment-box .content,
        .template04 .billing-box .content{
            border-top: 6px solid #cc0000;
            border-left: 1px solid #a9a9a9;
            border-right: 1px solid #a9a9a9;
            border-bottom: 1px solid #a9a9a9;
            padding: 10px 20px;
            margin-top: 5px;

        }
        .template04 .top-main-if{
            float: left;
            width: 100%;
            clear: both;
        }
        .template04 .bottom-main-info{
            clear: both;
            margin: 0 3.6% 0 3.6%;
            max-width: 92.8%;
        }
        .template04 .grandtotal{background: #ffe8e8; font-size: 20px;}
        .template04 .grandtotal tfoot td{border-top: 7px solid #fff!important;text-align:right;padding:5px 20px;}
        .template04 .grandtotal tfoot td.label strong{line-height: 40px;}
        .template04 .grandtotal tbody td{border: 0 none; text-align: right;}
        .template04 table thead td{
            font-size: 18px;
            color: <?php echo '#' . $color; ?>;
            text-align: center;				 
            font-weight: bold;
            padding: 12px 20px;
            text-transform: uppercase;
            vertical-align: middle;
        }
        .template04 .items td {                
            /*border-bottom: 1px solid #d6d6d6;*/

        }
        .template04 .tbody-2{
            border-bottom: 1px solid #d6d6d6;
        }
        .template04 .tbody-2 td{
            background: #e9e9e9;				
        }
        .template04 .items-tr{
            background: #e9e9e9;				
        }
        .template04 .table-data tbody {
            text-align: left;
        }
        .template04 .table-data tbody td{                
            padding: 12px 20px;
            color: #2f2f2f;
        }
        .template04 .table-data tbody td.a-right{                
            text-align: right;
        }
        .template04 .table-data tbody td.last{                
            text-align: right;
        }

        .template04 div.title{
            width:<?php echo $title_width ?>
        }

        .template04 .footer-total{width:100%}
        .template04 .grand_total{color: #e00000;
                     font-size: 20px;
                     font-family: 'Ubuntu';}
        .template04 .row-grandtotal{
            border-top: 0.1mm solid #fff;
        }
        .template04 .list-detail{
            border-style:solid;
            border-width:0px 0px 6px 0px;
            border-color:#cc0000;

        }
        .template04 .show-product-chan{
            background-color:#D6D6D6;
        }
        .template04 .show-product-le{
            background-color:#fff;
        }
        .footer-template04{
            background:  <?php echo '#' . $color; ?>;
            color: #FFFFFF;
            font-size: 14px;				
            margin-top: 10px;
            padding: 10px 5%;
            text-align: center;
            width: 90%;
            position: absolute;
            bottom: 0;
        }
        .template04 div.footer-text{
            font-family:  'Ubuntu';
            color:#FFFFFF;
        }
        .template04 .term-conditions{
            margin-top:20px;
            margin-bottom:30px;
        }


        /*********************/
        /*Totals*/
        .template04 .totals{
            float: right;
            width: 49%;
            background: #e9e9e9;
        }
        .template04 .body-total{
            height: auto;
            float: right;
            margin: 10px;
        }
        .template04 .total-row{
            width: 100%;
            text-align: right;
            float: right;
            padding: 5pt 0pt;
        }
        .template04 .total-row-grand{ border-top: 1px solid #fff; }
        .template04 .total-label{
            font-family: 'Ubuntu';
            font-size: 11pt;
            color: #2F2F2F;
            width: 45%;
            float: left;
            height: 22pt;
        }
        .template04 .total-value{
            font-size: 11pt;
            width: 45%;
            height: 22pt;
            float: right;
        }
        .template04 .grand-total, .template04 .grand-total-value, .template04 .grand-total-label {
            font-family: 'Ubuntu';
            font-weight: bold;
            font-size: <?php echo $font_size_2 ?>;
        }
        .template04 .grand-total-value{
            color: #bf2323;
        }
        /*end totals*/
        /*******************/

        .template04 .note{
            padding: 20px 5%;border: 1px solid #D6D6D6;
        }
        .template04 .note-box{
            width: 49%;
            float: left;
        }
        /*infomations*/
        .template04 .general-info{ display: block; width:100%; float: left; font-family: 'Ubuntu Light';font-size: 15px; }
        .template04 .general-info .info-label{ font-weight: bold; }
        /*        .general-info .info-value{ display: inline-block; }*/

         #container-inner{
            position: relative;
            /*            width: 90%;*/
            height: auto;
            padding: 0px;
            margin: 0 auto;
            border: 0px;
            word-wrap: normal;
            padding-bottom:<?php echo $footerHeight+10;?>px;
            /*display:inline-block;*/
        }
        .template04 .p-note, .template04 .term-conditions p{
            text-align: justify;
        }
    </style>
</head>
<div id="container-inner" class="template04">
    <div class="myheader-iv" style="padding-top: 20px; padding-bottom: 20px;">
        <div class="top-header-iv">
            <div class="title-page-iv1">
                <div class="order1 title-color contenteditable color-theme"  contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true" style="">
                    <?php echo $this->_locale->translate('Invoice'); ?></div>  

                <div class="barcode" style="">
                    <?php if ($barcode == '1' && $barcode_type): ?>
                        <barcode code='<?php echo $barcode_invoice; ?>' type='<?php echo $barcode_type; ?>' />
                    <?php endif; ?>
                </div>
            </div>

            <div class="box-logo ajaxupload" style="margin-top: 0px;text-align: right; float: right" info-img="company_logo">
                <?php echo ($logo) ? '<img width="160" src="' .$logoUrlConverter. '" />' : ''; ?>
            </div>
        </div>
        <div class="bottom-header-iv"  contextmenu-type="main">
            <div class="id-invoice-iv">
                <div  contextmenu-type="main" style="font-family: 'Ubuntu Medium';font-size: 26px;" class="content contenteditable">
                    <span class="color-text contenteditable" title="Click to edit, right-click to insert variable"  contenteditable="true" style="font-family: 'Ubuntu Medium';font-size: 26px;">#{{var invoice_increment_id}}</span><br/>
                    <span class="color-text contenteditable" title="Click to edit, right-click to insert variable"  contenteditable="true" style="color: #010101;font-size: 18px;">{{var invoice_created_at}}</span>
                </div>
                <!--Edit by Zeus 15/01/2014-->
                <div class="status color-text contenteditable"  contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true" style="margin-top: 5px;">
                    <span style="font-weight: bold;">Status: </span> {{var invoice_state}}
                </div>
                <!--end edit-->
            </div>
            <div contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true" class="box-infomations autogrow info-iv contenteditable">
                <?php if ($name): ?><span class="title-color" title="Click to edit, right-click to insert variable" style="display: block; font-weight: bold; font-size: 18px; color: <?php echo '#' . $color; ?>; width:100%; float: left;font-family: 'Ubuntu';text-transform: uppercase;" info-text="company_name"><?php echo $name ?></span><br/><?php endif; ?>
                <?php if ($address): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block; font-family: 'Ubuntu Light'; font-size: 14px;width:100%;float: left;"><strong><?php echo $this->__('Address:') ?> </strong><info info-text="company_address"><?php echo $address ?></info></span><br/><?php endif; ?>		 
                <?php if ($email): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block;width:100%;float: left; "><strong> <?php echo $this->__('Email:') ?> </strong> <info info-text="company_email"><?php echo $email ?></info></span><br/><?php endif; ?>
                <?php if ($phone): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block; width:100%;float: left; "><strong><?php echo $this->__('Tel:') ?> </strong><info info-text="company_telephone"><?php echo $phone ?></info></span><br/><?php endif; ?>
                <?php if ($fax): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block;width:100%;float: left; "><strong><?php echo $this->__('Fax:') ?> </strong><info info-text="company_fax"><?php echo $fax ?></info></span><br/><?php endif; ?>
                <?php if ($businessId): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block;width:100%;float: left; "><strong><?php echo $this->__('Business Id:') ?> </strong><info info-text="business_id"><?php echo $businessId ?></info></span><br/><?php endif; ?>
                <?php if ($vatnumber): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block;width:100%;float: left; "><strong><?php echo $this->__('VAT Number:') ?> </strong><info info-text="vat_number"><?php echo $vatnumber ?></info></span><br/><?php endif; ?>
                <?php if ($vatoffice): ?><span class="color-text" title="Click to edit, right-click to insert variable" style="display: block;width:100%;float: left; "><strong><?php echo $this->__('VAT Office:') ?> </strong><info info-text="vat_office"><?php echo $vatoffice ?></info></span><br/><?php endif; ?>

            </div>
        </div>												
    </div>


    <div class="main-content">
        <div class="top-main-if">
            <div class="info-cus">				
                <div class="billing-box">
                    <div class="title1">
                        <span title="Click to edit, right-click to insert variable"  contenteditable="true" class="contenteditable title-color title-label"><?php echo $this->_locale->translate('Billing Address') ?></span></span>
                    </div>
                    <div class="content contenteditable">
                        <address contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true">{{var invoice_billing_address}}</address>
                    </div>
                </div>

                <div class="shipping-add-box">
                    <div class="title1">
                        <span title="Click to edit, right-click to insert variable"  contenteditable="true" class="title-color title-label contenteditable"><?php echo $this->_locale->translate('Shipping Address') ?></span>
                    </div>
                    <div class="content contenteditable">
                        <address contextmenu-type="main"  title="Click to edit, right-click to insert variable"  contenteditable="true" class="contenteditable">{{var invoice_shipping_address}}</address>
                    </div>
                </div>		
            </div>

            <div class="info-cus" style="margin-top: 25px; margin-bottom: 25px;">		
                <div class="payment-box">
                    <div class="title1">
                        <span contenteditable="true"  title="Click to edit..."  class="contenteditable title-color title-label"><?php echo $this->_locale->translate('Payment Method') ?></span>
                    </div>				
                    <div class="content contenteditable" contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true">
                        {{var invoice_payment_method}}
                    </div>
                </div>

                <div class="shipping-box">
                    <div class="title1">
                        <span contenteditable="true" title="Click to edit..."  class="contenteditable title-color title-label"><?php echo $this->_locale->translate('Shipping Method') ?></span>
                    </div>
                    <div class="content contenteditable" contextmenu-type="main" title="Click to edit, right-click to insert variable"   contenteditable="true">
                        {{var invoice_shipping_method}}
                    </div>
                </div>		
            </div>
        </div>
    </div>
    <!--<h3 style="font-size: 12pt; color: rgb(47, 79, 78);  text-transform: uppercase;font-weight:bold">Ordered Items</h3>-->
    <div class="bottom-main-info">
        <table id="table-item" class="items table-data " width="100%" style="font-size: 14px; border-collapse: collapse;" cellpadding="6">
            <thead style="border-bottom: 6px solid #cc0000;">
                <tr class="style-border-color" style="height:30px;">
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="25%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:left;"><?php echo $this->_locale->translate('PRODUCT'); ?></th>
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="13%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:left;"><?php echo $this->_locale->translate('SKU'); ?></th>
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="13%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:right;"><?php echo $this->_locale->translate('PRICE'); ?></th>
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="18%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:right;"><?php echo $this->_locale->translate('QTY'); ?></th>
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:right;"><?php echo $this->_locale->translate('TAX'); ?></td>
                    <th class="items-color title-color title-label contenteditable" contenteditable="true" width="21%" style="font-family:'Ubuntu';text-transform:uppercase;text-align:right;"><?php echo $this->_locale->translate('SUBTOTAL'); ?></th>
                </tr>
            </thead>
            <tbody>
                <!-- ITEMS HERE -->
                <!--            ##productlist_start##--> 
                <tr class="items-tr background-items">
                    <td class="color-text contenteditable" title="Click to edit..."  contenteditable="true" contextmenu-type="item" align="left">{{var items_name}}<br/>{{var items_product_options}}</td>
                    <td class="color-text contenteditable" title="Click to edit, right-click to insert variable"  contenteditable="true" contextmenu-type="item" align="left">{{var items_sku}}</td>
                    <td class="color-text contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_price}}</td>
                    <td class="color-text contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item"  contenteditable="true" align="right">
                        {{var items_qty}}
                    </td>
                    <td class="color-text contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_tax_amount}}</td>
                    <td class="color-text contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>
                </tr>
                <!--            ##productlist_end##-->
            </tbody>
        </table>

        <div class="after-item" style="width:100%;display:inline-block; padding-top:20px;">
            <div class="invoice-totals" style="width:100%; float: left;margin-top: 20px;">
                <div class="note-box">
                    <?php if ($note): ?>
                        <div contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true" class="color-text note p-note contenteditable">
                            <strong>Note: </strong>
                            <span class="info-value" info-text="note"><?php echo $note; ?></span>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="totals autogrow contenteditable background-items" title="Click to edit, right-click to insert variable" contenteditable="true">
                    <div class="body-total" title="Click to edit, right-click to insert variable">
                        <div class="total-row background-items" contextmenu-type="main">
                            <div class="total-label color-text"><?php echo $this->_locale->translate('Subtotal'); ?></div>
                            <div class="total-value color-text">{{var invoice_subtotal}}</div>
                        </div>
                        <div class="total-row background-items" contextmenu-type="main">
                            <div class="total-label color-text"><?php echo $this->_locale->translate('Tax'); ?></div>
                            <div class="total-value color-text">{{var invoice_tax_amount}}</div>
                        </div>
                        <div class="total-row background-items" contextmenu-type="main">
                            <div class="total-label color-text"><?php echo $this->_locale->translate('Shipping'); ?></div>
                            <div class="total-value color-text">{{var invoice_shipping_amount}}</div>
                        </div>
                        <div class="total-row total-row-grand background-items" contextmenu-type="main">
                            <div class="total-label color-text grand-total"><?php echo $this->_locale->translate('Grand Total'); ?></div>
                            <div class="total-value color-text grand-total grand-total-value">{{var invoice_grand_total}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="term-conditions">
            <?php if ($term): ?>
                <div contextmenu-type="main" contenteditable="true" title="Click to edit, right-click to insert variable" class="contenteditable color-text term p-note"><strong>Term: </strong><span class="info-value" info-text="terms_conditions"><?php echo $term; ?></span></div>
            <?php endif; ?>
        </div>
    </div>
    <br />
</div>

<div id="footer" class="footer-template04 color-text style-color theme-color" name="myfooter" style="height: <?php echo $footerHeight;?>px;">
    <div contextmenu-type="main" contenteditable="true" title="Click to edit, right-click to insert variable" class="color-text contenteditable" style="padding-left:3.5%;padding-top: 10px;width: 100%; " info-text="footer"><?php if ($footer) echo $footer; ?></div>
</div>
<script type="text/javascript">
//    $(function() {
//        if ($('#footer').length > 0) {
//            var footer = $('#footer').height();
//            $('#container-inner').css('padding-bottom', footer + 'px');
//        }
//    });
</script>

