<div class="ruffle-popup card-alert" id="ruffle-popup-card-alert" style="display: block">
    <div class="ruffle-popup-content">
        <span class="popup-close">x</span>
        <h2 class="popup-title">
            <?php if($this->getData('title')): ?>
                <?php echo $this->getData('title') ?>
            <?php else: ?>
                <?php echo $this->__("CAN'T ADD CREDIT CARD") ?>
            <?php endif; ?>
        </h2>
        <div class="content" >
            <?php if($this->getData('error_message')): //debit card?>
                <p><?php echo $this->getData('error_message') ?></p>
            <?php else: ?>
                <?php if($this->getData('error_code')): ?>
                    <?php $text = $this->__("THIS CREDIT CARD IS NOT VALID (%s).", $this->getData('error_code')) ?>
                <?php else: ?>
                    <?php $text = $this->__("THIS CREDIT CARD ALREADY EXISTS.") ?>
                <?php endif; ?>
                <p><?php echo $text ?></p>
                <p><?php echo $this->__("PLEASE TRY A DIFFERENT CARD.") ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    jQuery('.popup-close').on('click', function () {
        if ($('ruffle-popup-card-alert')) {
            $('ruffle-popup-card-alert').hide();
        }
    });
</script>
