<?php $_customer = Mage::getSingleton('customer/session')->getCustomer();
if (!$_customer->getId()) return;
?>
<?php $omiseHelper = Mage::helper('ruffle/omise') ?>
<?php $customerApiId = $_customer->getCustomerApiId(); ?>
<?php $_code = 'omise_gateway'; ?>
<?php $listCard = $omiseHelper->getListCardCustomerOmise($customerApiId);
$check = $this->getCheck();
?>
<?php $defaultIdCard = $omiseHelper->getDefaultIdCardCustomerOmise($customerApiId) ?>
<div class="ruffle-popup ruffle-card-list" id="ruffle-card-list" style="display: block">
    <div class="ruffle-popup-content">
        <span class="popup-close">x</span>
        <?php if($check['use_creditcard']): ?>
        <div class="step-bar">
            <ul>
                <li class="">
                    <span><?php echo $this->__('Term & Condition') ?></span>
                </li>
                <li class="active">
                    <span><?php echo $this->__('Payment') ?></span>
                </li>
                <li>
                    <span><?php echo $this->__('Information join') ?></span>
                </li>
            </ul>
        </div>
        <?php endif; ?>
        <?php if ($listCard): ?>
            <h2 class="popup-title"><?php echo $this->__('Choose Credit/Debit Card To Payment') ?></h2>
            <p style="text-align: center;color: red"><?php echo $this->__('*ระบบจะทันการตัดเงินอัตโนมัติทันทีหากท่านได้รับสิทธิ์ซื้อสินค้า') ?></p>
        <?php else: ?>
            <h2 class="popup-title"><?php echo $this->__('Add new credit/debit card') ?></h2>
            <p style="text-align: center;color: red"><?php echo $this->__('*ระบบจะทันการตัดเงินอัตโนมัติทันทีหากท่านได้รับสิทธิ์ซื้อสินค้า') ?></p>
        <?php endif; ?>
        <div class="ruffle-popup-form">
            <div class="fieldset">
                <?php if ($listCard && !empty($listCard['data'])): ?>
                    <div id="list-omise-card" class="list-omise-card">
                        <ul class="list-omise-card">
                            <?php foreach ($listCard['data'] as $card): ?>
                                <li class="<?php echo $card['brand'] ?>">
                                    <input type="radio" name="payment[omise_card_id]" id="<?php echo $card['id'] ?>"
                                           value="<?php echo $card['id'] ?>"
                                           <?php if ($card['id'] == $defaultIdCard): ?>checked="checked"<?php endif; ?>
                                           class="radio validate-one-required-by-name"/><label
                                            for="<?php echo $card['id'] ?>"><span><?php echo '**** **** **** ' . $card['last_digits']; ?></span>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                            <li class="control new-card">
                                <input type="radio" name="payment[omise_card_id]" id="new_omise_card"
                                       value="new_omise_card"
                                       class="radio validate-one-required-by-name"/><label
                                        for="new_omise_card">
                                    <span><?php echo $this->__('Add new credit/debit card') ?></span></label>

                            </li>
                        </ul>
                    </div>
                <?php endif; ?>
                <div <?php if ($listCard && count($listCard['data']) > 0): ?>style="display: none" <?php endif; ?>
                     id="omise_new_card_form">
                    <ul class="form-list omise_new_card_form" id="card_form_omise_gateway">
                        <input data-omise="omise_token" type="hidden" name="card[omise_token]">

                        <li class="fields">
                            <label for="<?php echo $_code ?>_cc_number"
                                   class="required"><em>*</em><?php echo $this->__('Card number') ?></label>
                            <div class="input-box">
                                <input type="text" maxlength="16" autocomplete="off" data-omise="number"
                                       class="input-text required-entry validate-cc-number validate-cc-type required"
                                       id="<?php echo $_code ?>_cc_number"
                                       title="<?php echo $this->__('Card number') ?>" value=""/>
                            </div>
                        </li>

                        <li class="fields">
                            <label for="<?php echo $_code ?>_cc_owner"
                                   class="required"><em>*</em><?php echo $this->__('Cardholder Name'); ?>
                            </label>
                            <div class="input-box">
                                <input type="text" data-omise="holder_name" id="<?php echo $_code ?>_cc_name"
                                       class="input-text required-entry"
                                       title="<?php echo $this->__('Cardholder Name') ?>"
                                />
                            </div>
                        </li>

                        <li id="omise_gateway_cc_type_exp_div" class="omise-exp-date">
                            <label for="<?php echo $_code ?>_expiration"
                                   class="required"><em>*</em><?php echo $this->__('Expiry Date') ?></label>
                            <div class="input-box">
                                <div class="v-fix">
                                    <select data-omise="expiration_month" id="<?php echo $_code ?>_expiration">
                                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="v-fix">
                                    <select data-omise="expiration_year" id="<?php echo $_code ?>_expiration_yr">
                                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </li>
                        <li class="fields" id="omise_gateway_cc_type_cvv_div">
                            <label for="<?php echo $_code ?>_cc_cid"
                                   class="required"><em>*</em><?php echo $this->__('CVV/CVV2') ?></label>
                            <div class="input-box">
                                <div class="input-box">
                                    <div class="v-fix">
                                        <input autocomplete="off" data-omise="security_code"
                                               type="text"
                                               title="<?php echo $this->__('CVV/CVV2') ?>"
                                               class="input-text cvv required-entry validate-cc-cvn"
                                               id="<?php echo $_code ?>_cc_cid"
                                               value=""/>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="control">
                                <input type="checkbox" value="1" name="payment[is_saved_card]"
                                       id="customer-card-detail"
                                       class="checkbox"/>
                                <label for="customer-card-detail"><?php echo $this->__('Save Card') ?><p class="raffle-save-card"><?php echo $this->__('Information is encrypted and securely stored') ?></label>
                            </div>
                            <div class="control">
                                <input type="checkbox" value="1" name="payment[accept_term]" id="accept_term"
                                       class="required-entry checkbox"/>
                                <label for="accept_term"><?php echo $this->__('Accept Term & Condition') ?></label>
                            </div>
                        </li>
                    </ul>
                </div>

                <div class="button-set">
                    <button type="button" id="submit-information-personal"
                            class="button" onclick="ruffleCreateOmiseToken(this)">
                        <span><span><?php echo $this->__('CONFIRM'); ?></span></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $j('input[type=radio][name="payment[omise_card_id]"]').on('change', function (event) {
        $j('input[type=radio][name="payment[omise_card_id]"]').each(function (k,ele) {
            ele.removeAttribute('checked');
        });
        $('omise_new_card_form').hide();
        $j('input[type=radio][name="payment[omise_card_id]"]:checked').trigger('click');
        var value = $j('input[type=radio][name="payment[omise_card_id]"]:checked').val();
        event.currentTarget.setAttribute('checked','checked');
        // $j('input[type=radio][name="payment[omise_card_id]"]:checked').attr("checked", "checked");
        // $j('input[type=radio][name="payment[omise_card_id]"]').val(value);
        switch (value) {
            case 'new_omise_card':
                $('omise_new_card_form').show();
                break;
            case 'transfer':
                break;
        }
    });
    jQuery('.popup-close').on('click', function () {
        if ($('ruffle-form-info')) {
            $('ruffle-form-info').hide();
        }
        // if($('ruffle-card-info') $('ruffle-card-info').hide();
        if ($('ruffle-card-list')) {
            $('ruffle-card-list').hide();
        }
        if ($('ruffle_term_list')) {
            $('ruffle_term_list').hide();
        }
    });
</script>
