<?php

class Tigren_Kpayment_Model_Payment_Credit extends Mage_Payment_Model_Method_Abstract {

    protected $_code  = 'kpayment_credit';

    protected $_formBlockType = 'kpayment/form_credit';

    protected $_infoBlockType = 'kpayment/info_credit';

    protected $_isGateway       = true;

    protected $_canAuthorize    = true;

    protected $_canCapture      = true;

    protected $_canOrder        = true;

    public function isAutoCapture()
    {
        return $this->getConfigData('payment_action') === Mage_Payment_Model_Method_Abstract::ACTION_AUTHORIZE_CAPTURE;
    }

    public function is3Dsecure()
    {
        return $this->getConfigData('secure_support');
    }

    public function capture(Varien_Object $payment, $amount)
    {
        return $this;
    }

    public function initialize($paymentAction, $stateObject)
    {
        return parent::initialize($paymentAction, $stateObject); // TODO: Change the autogenerated stub
    }

    public function assignData($data)
    {
//        $info = $this->getInfoInstance();
//
//        if ($data->getCustomFieldOne())
//        {
//            $info->setCustomFieldOne($data->getCustomFieldOne());
//        }
//
//        if ($data->getCustomFieldTwo())
//        {
//            $info->setCustomFieldTwo($data->getCustomFieldTwo());
//        }

        return $this;
    }

    public function validate()
    {
        parent::validate();
//        $info = $this->getInfoInstance();
//
//        if (!$info->getCustomFieldOne())
//        {
//            $errorCode = 'invalid_data';
//            $errorMsg = $this->_getHelper()->__("CustomFieldOne is a required field.\n");
//        }
//
//        if (!$info->getCustomFieldTwo())
//        {
//            $errorCode = 'invalid_data';
//            $errorMsg .= $this->_getHelper()->__('CustomFieldTwo is a required field.');
//        }
//
//        if ($errorMsg)
//        {
//            Mage::throwException($errorMsg);
//        }

        return $this;
    }

    public function isAvailable($quote = null)
    {
        return true;
    }

//    public function getOrderPlaceRedirectUrl()
//    {
//        return Mage::getUrl('custompaymentmethod/payment/redirect', array('_secure' => false));
//    }
}