<?php
$templateCode = Mage::helper('pdfinvoiceplus/pdf')->getTemplateCode();
$invoice = $this->getInvoice();
$payment_method = $invoice->getOrder()->getPayment()->getMethodInstance();
$shipping_method = $invoice->getOrder()->getShippingDescription();
$template = Mage::helper('pdfinvoiceplus/pdf')->getUsingTemplate();
$logo = $template->getCompanyLogo();
$address = $template->getCompanyAddress();
$name = $template->getCompanyName();
$email = $template->getCompanyEmail();
$phone = $template->getCompanyTelephone();
$fax = $template->getCompanyFax();
$note = $template->getNote();
$footer = $template->getFooter();
$color = $template->getColor();
$color = $color ? $color: '78C145';
$vat = $template->getVatNumber();
$bussinessId = $template ->getBusinessId();
$pageFormat = $template->getFormat();
$display_images = $template->getDisplayImages();
$orientation = $template->getOrientation();
if ($orientation == 0) {
    if ($pageFormat == 'A5') {
        $title_width = '74%';
    } else {
        $title_width = '80%';
    }
} elseif ($orientation == 1) {
    if ($pageFormat == 'A5') {
        $title_width = '78.5%';
    } else {
        $title_width = '83%';
    }
}
$barcode = $template->getBarcode();
$barcode_type = $template->getBarcodeType();
$barcode_value = Mage::helper('pdfinvoiceplus/pdf')->getBarcodeValue();
$term = $template->getTermsConditions();
$vatoffice = $template->getVatOffice();
$status = $invoice->getState();
if($status == 1){
    $status = 'Pending';
}elseif($status ==2){
    $status = 'Paid';
}else{
    $status = 'Canceled';
}
?>
<html>
    <head>
        <style>
            *{margin: 0; padding: 0;}
            body {
                font-size: 12px;
                max-width:100%;
                margin-left:4.7%;
                font-family: "Ubuntu", "Ubuntu Regular", arial;	
                font-size-adjust: none;
            }
            .main-content {
                width:80%;
                margin: 0 auto 0;
                margin-top: -60px;
            }

            p {    margin: 0pt;
            }
            td { vertical-align: top; }
            .items td {
                border-left: 0.1mm solid #fff;
                border-right: 0.1mm solid #fff;
            }
            table thead td { background-color: <?php echo '#'.$color;?>;
                             color: #fff;
                             text-align: center;
                             border: 0.1mm solid #fff;
                             font-weight: bold;
                             padding: 7px 10px;
            }
            .table-data tbody td{
                background: #e8e8e8;
                padding: 5px 10px;
                color: #2f2f2f;
            }
            .items td.blanktotal {
                background-color: #FFFFFF;
                border: 0mm none #fff;
                border-top: 0.1mm solid #fff;
                border-right: 0.1mm solid #fff;
            }
            .items td.totals {
                background: none repeat scroll 0 0 #FFFFFF;
                border: 0 none;
                text-align: right;
            }
            .top-title span {
                display: block;
                font-size: 15px;
                color: #000;
            }
            .title-color{
                color: #FFFFFF;
                font-family: 'Ubuntu';
                font-size: 12px;
                font-weight: bold;
                text-transform: uppercase;
            }
            div.title{
                background: <?php echo '#' . $color; ?>;                
                color: <?php echo '#' . $color; ?>;
                margin-bottom: 0;
                height: 16px;
                padding: 5px 10px;
                position: relative;
                width: <?php echo $title_width; ?>;
                float: left;
            }
            div.arrow{
                height:0px;
                width: 0px;
                border-top: 13px solid transparent;
                border-bottom: 13px solid transparent;
                border-left: 13px solid <?php echo '#' . $color; ?>;
                border-color: #fff #fff #fff <?php echo '#' . $color; ?>;
            }
            /*blanka*/
            #customer-address{
                width:100%;
            }
            #payment-shipping{
                width:100%;
            }
            .first-block{
                width:49%;
            }
            .billing-address{
                float:left;
            }
            .shipping-address{
                float:right;
            }
            .second-block{
                width:49%;
            }
            .payment-method{
                float:left;
            }
            .shipping-method{
                float:right;
            }
            .top-title span span{
                font-family: 'Ubuntu';
                text-align: left; 
                font-size: 30px; 
                font-weight: normal; 
                color: #000;
                line-height: 30px !important;
            }
            .company-logo{
                float:left;
                width: 49%;
            }
            .company-address{
                float:right;
                width:40%;
                text-align: right;
            }
            .company-address .company-name{
                width: 100%;
            }
            .company-address .company-contact{
                width: 100%;
            }
            
            .header-page{
                background-image: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/' . $templateCode . '/images/bg-body.png'; ?>");
                background-repeat:  no-repeat;
                background-position:  top center;
                padding: 10px 10% 0;
                /*width:100%;*/
                height: 150px;
                border-top: 5px solid <?php echo '#'.$color;?>;
            }
            .footer-page{
                background-image: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/' . $templateCode . '/images/bg-footer.png'; ?>");
                background-repeat:  no-repeat;
                background-position:  bottom center;
                height:150px;
                
                
                border-bottom: 5px solid <?php echo '#'.$color;?>;
                position:absolute;
                bottom:0;
                width:100%;
            }
            .footer-text{
                width:90%;
                margin: 0 auto;
                text-align:center;
                /*margin-top:70px;*/
                padding-top: 110px;
            }
            .a-right {
                text-align: right !important;
            }
            /*invoice total*/
            .invoice-totals{
                margin-right:4.7%;
                margin-top:50px;
            }
            .invoice-totals table tr td{
                color: #000000;
                font-family: 'Ubuntu';
                font-weight: bold;
                font-size: 11px;
                background: none repeat scroll 0 0 #FFFFFF;
                border: 0 none;
                text-align: right;
                padding: 5px 10px;
            }
            .invoice-totals table tr td.label{
                width: 81%;
            }
            .grand_total {
              color: #bf2323;
              font-size: 15px;
            }
            .invoice-totals table tfoot tr td.grand-label {
              border-top: 1px solid #D7D7D7 !important;
            }
            .invoice-totals table tfoot tr td.grand-emph {
              border-top: 1px solid #D7D7D7 !important;
            }
            .table-data tbody td {
                padding: 5px;
            }
            .barcode-invoice{
                margin-top:10px;
                margin-bottom:10px;
            }
            /*viet*/
            .totals {
                width: 100%;
            }
            .body-total {
                width: 100%;
            }
            .totals-li {
                float: left;
                width: 100%;
                list-style: none outside none;
                padding: 5px 10px;
            }
            .totals-label {
                float: left;
                font-weight: bold;
                text-align: right;
                width: 75%;
                padding:5px 2px;
            }
            .totals-value{
                background: none repeat scroll 0 0 #FFFFFF;
                border: 0 none;
                color: #000000;
                font-family: 'Ubuntu';
                font-size: 11px;
                font-weight: bold;
                padding: 5px 0px;
                text-align: right;
            }
            .row-grandtotal{
                border-top:0.1mm solid #D7D7D7;
            }
            .term-conditions{
                margin-top:20px;
                margin-bottom:30px;
            }
        </style>
    </head>
    <body>
        <div class="header-page">
            <div class="company-logo">
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).  'magestore/pdfinvoiceplus/'.$logo ;?>" width="161"/>
            </div>
            <div class="company-address " style="margin-right:3%">
                <div class="company-name" style="font-weight: bold; font-size: 12px; color: #010101; font-family: 'Ubuntu';text-transform: uppercase;">
                    <?php echo $name; ?>
                </div>
                <div class="company-contact">
                    <?php if ($address): ?><p> <?php echo $address; ?></p><?php endif; ?>
                    <?php if ($email): ?><p> <?php echo $this->__('Email') ?>: <?php echo $email; ?></p><?php endif; ?>
                    <?php if ($phone): ?><p> <?php echo $this->__('Phone') ?>:  <?php echo $phone; ?><?php if ($fax): ?> | <?php echo $this->__('Fax') ?>: <?php echo $fax; ?><?php endif; ?></p> <?php endif; ?>
                    <?php if ($vat): ?><p> <?php echo $this->__('Vat Number') ?>: <?php echo $vat; ?></p><?php endif; ?>
                    <?php if($vatoffice):?><p> <?php echo $this->__('Vat Office') ?>: <?php echo $vatoffice; ?></p><?php endif;?>
                    <?php if ($bussinessId): ?><p> <?php echo $this->__('Business Id') ?>: <?php echo $bussinessId; ?></p><?php endif; ?>
                </div>
            </div>
        </div>
        <div class="main-content">
            <div class="top-title" style="width: 100%;clear: both;margin-bottom: 15px;">
                <div style="float:left;width: 49%;">
                    <div style="color: <?php echo '#'.$color;?>; font-weight:bold;font-family: 'Ubuntu';text-align:left; font-size: 30px;margin-top:28px"><?php echo $this->__('Invoice')?></div>
                    <span style="font-size:28px"><?php echo Mage::app()->getStore()->formatPrice($invoice->getGrandTotal()); ?></span>
                    <?php if ($status): ?><p> <?php echo $this->__('Status') ?>: <?php echo $status; ?></p><?php endif; ?>
                </div>
                <div style="float:right;width: 40%; margin-top: 65px;text-align: right;vertical-align: bottom;margin-right:4.7%">
                    <span style="font-family: 'Ubuntu Medium'"><?php echo "#".$invoice->getIncrementId();?></span>
                    <br/>
                    <span style="color: #010101;font-size: 11px;"><?php echo $this->formatDate($invoice->getCreatedAt(), 'medium', true);?></span>
                </div>
            </div>
            <div id="customer-address">
                <div class="first-block billing-address">
                    <div class="title">
                        <span class="title-color">
                            <?php echo $this->__('Billing Address') ?>
                        </span>
                    </div>
                    <div class="arrow" style="float:left; "></div>
                    <div style="padding: 12px;font-size: 12px;  width: 100%;"><div class="entry-edit-head">
                            <div class="tools"><?php echo $this->getAddressEditLink($invoice->getBillingAddress()) ?></div>
                        </div>
                        <fieldset>
                            <address><?php echo $invoice->getBillingAddress()->getFormated(true) ?></address>
                        </fieldset>
                    </div>
                </div>
                
                <!--div class="arrow" style="float:right;width:4%;"></div-->
                <div class="first-block shipping-address">
                    <div class="title">
                        <span class="title-color">
                            <?php echo $this->__('Shipping Address') ?>
                        </span>
                    </div>
                    <div class="arrow" style="float:left;"></div>
                    <div style="padding: 12px;font-size: 12px;  width: 209px; float: left;"><div class="entry-edit-head">
                            <div class="tools"><?php echo $this->getAddressEditLink($invoice->getShippingAddress()) ?></div>
                        </div>
                        <fieldset>
                            <?php if($invoice->getShippingAddress()): ?>
                            <address><?php echo $invoice->getShippingAddress()->getFormated(true) ?></address>
                            <?php else: ?>
                            <address><?php echo $this->__('No Shipping Address'); ?></address>
                            <?php endif; ?>
                        </fieldset>
                    </div>
                </div>
               
            </div>

            <div id="payment-shipping">
                <div class="second-block payment-method">
                    <div class="title">
                        <span class="title-color">
                            <?php echo $this->__('Payment Method') ?>
                        </span>
                    </div>
                    <div class="arrow" style="float:left;"></div>
                    <div style="padding: 10px; width: 209px; float: left;font-size: 12px; "><?php echo $payment_method->getTitle(); ?></div>
                </div>
                
                <div class="second-block shipping-method">
                    <div class="title">
                        <span class="title-color">
                            <?php echo $this->__('Shipping Method') ?>
                        </span>
                    </div>
                    <div class="arrow" style="float:left;"></div>
                    <div style="padding: 10px; width: 209px; float: left;font-size: 12px; ">
                        <?php if($shipping_method): ?>
                            <?php echo $shipping_method; ?>
                            <?php else: ?>
                            <?php  echo $this->__('No Shipping Method'); ?>
                            <?php endif; ?>
                    </div>		
                </div>
                
            </div>
            
            <!--<h3 style="font-size: 12pt; color: rgb(47, 79, 78);  text-transform: uppercase;font-weight:bold">Ordered Items</h3>-->
            <table class="items table-data" style="font-size: 12px; width:95.3%; border-collapse: collapse;" cellpadding="0">
                <thead>
                    <tr>
                        <td width="28%" style="font-family:'Ubuntu';"><?php echo $this->__('Product') ?></td>
                        <?php if($display_images==1):?>
                            <td width="12%" style="padding: 5px; font-family:'Ubuntu';"><?php echo $this->__('Image') ?></td>
                        <?php endif;?>
                        <td width="10%" style="font-family:'Ubuntu';"><?php echo $this->__('Price') ?></td>
                        <td width="auto" style="font-family:'Ubuntu';"><?php echo $this->__('Qty') ?></td>
                        <td width="10%" style="font-family:'Ubuntu';"><?php echo $this->__('Subtotal') ?></td>
                        <td width="5%" style="font-family:'Ubuntu';"><?php echo $this->__('Tax') ?></td>
                        <td width="5%" style="font-family:'Ubuntu';"><?php echo $this->__('Discount') ?></td>
                        <td width="10%" style="font-family:'Ubuntu';"><?php echo $this->__('Row Total') ?></td>
                    </tr>
                </thead>
                <tbody>
                    <!-- ITEMS HERE -->
                    <?php $_items = $invoice->getAllItems(); ?>
                    <?php foreach ($_items as $item): ?>
                        <?php if ($item->getOrderItem()->getParentItem()) continue;?>
                        <?php echo $this->getItemHtml($item) ?>
                        <?php echo $this->getItemExtraInfoHtml($item->getOrderItem()) ?>
                    <?php endforeach; ?>
                </tbody>
                
            </table>
            <?php 
                $totalBlock = $this->getLayout()->createBlock('pdfinvoiceplus/adminhtml_totals_invoice')
                        ->setTemplate('pdfinvoiceplus/sales/order/totals.phtml');
            ?>
            <div class="invoice-totals"><?php  echo $totalBlock->toHtml(); ?></div>
            <br/>
             <?php if($barcode == 1): ?>
                <p class="barcode-invoice" style="text-align: center;"><barcode code='<?php echo $barcode_value; ?>' type='<?php echo $barcode_type; ?>' /></p>
            <?php endif;?>
            <?php if ($note != ''): ?>
            <div style="text-align: left; font-style: italic;"><?php echo $note; ?></div>
            <?php endif; ?>
            <div class="term-conditions">
                <p class="barcode-invoice"><?php echo $term;?></p>
            </div>
            
        </div>
        <div class="footer-page">
            <div class="footer-text" style="">
                <?php echo $footer; ?>
            </div>
        </div>
    </body>
</html>