<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>

<script type="text/javascript">
    //<![CDATA[
        var preorderState = new PreorderStateGroup();
        preorderState.cartLabel = '<?php echo addslashes($this->getPreorderCartLabel()) ?>';
        preorderState.preorderMap = <?php echo json_encode($this->getGroupPreorderMap()) ?>;
        preorderState.messageMap = <?php echo json_encode($this->getGroupMessageMap()) ?>;

        document.observe("dom:loaded", function() {
            preorderState.start();
        });
    //]]>
</script>
