<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Coupons
 */
?>
<div class="discount">

    <?php if (($this->getRequest()->getControllerName() == 'onepage') && ('true' == (string)Mage::getConfig()->getNode('modules/GoMage_Checkout/active'))):?>

        <div class="lightcheckout-discount-form">

            <input type="hidden" name="remove" id="remove_coupone" value="0" />

            <h2><?php echo $this->__('Discount Codes') ?></h2>
            <div class="field-wrapper">  
              <input class="input-text" id="coupon_code" name="coupon_code" placeholder="<?php echo $this->__('Enter your coupon code if you have one') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = '<?php echo $this->__('Enter your coupon code if you have one') ?>'" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
              <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="if(!$('coupon_code').value){alert('<?php echo $this->__('Enter your coupon code if you have one.') ?>')}else{checkout.applyDisocunt(false);}" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
              <?php if(strlen($this->getCouponCode())): ?>
                  &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="checkout.applyDisocunt(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
              <?php endif;?>
            </div>
        </div>



        <?php if ($this->_getAppliedCoupons()): ?>
            <br />
            <h2><?php echo $this->__('Applied Coupons'); ?></h2>

            <table border="0" width="100%" cellpadding="4" cellspacing="0" style="padding-top: 3px;">

                <?php $couponCnt = 0; ?>
                <?php foreach ($this->_getAppliedCoupons() as $coupon): ?>
                    <tr style="padding-bottom: 3px;">
                        <td><?php echo $this->escapeHtml($coupon); ?></td>
                        <td style="text-align: right;">
                            <form id="discount-coupon-cancel-form-<?php echo $couponCnt; ?>" action="<?php echo $this->getUrl('amcoupons/checkout/cancelCoupon') ?>" method="post">
                                <input type="hidden" name="amcoupon_code_cancel" value="<?php echo $this->escapeHtml($coupon); ?>" />
                            </form>
                        </td>
                    </tr>
                    <?php $couponCnt++; ?>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    <?php else:?>
        <h2><?php echo $this->__('Discount Codes') ?></h2>
        <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
            <div class="discount-form">
                <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have any.') ?></label>
                <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <div class="field-wrapper">  
                  <input class="input-text" id="coupon_code" name="coupon_code" placeholder="<?php echo $this->__('Enter your coupon code if you have one') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = '<?php echo $this->__('Enter your coupon code if you have one') ?>'" value="" />
                  <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                </div>
            </div>
        </form>


        <?php if ($this->_getAppliedCoupons()): ?>
            <br />
            <h2><?php echo $this->__('Applied Coupons'); ?></h2>

            <table border="0" width="100%" cellpadding="4" cellspacing="0" style="padding-top: 3px;">

                <?php $couponCnt = 0; ?>
                <?php foreach ($this->_getAppliedCoupons() as $coupon): ?>
                    <tr style="padding-bottom: 3px;">
                        <td><?php echo $this->escapeHtml($coupon); ?></td>
                        <td style="text-align: right;">
                            <form id="discount-coupon-cancel-form-<?php echo $couponCnt; ?>" action="<?php echo $this->getUrl('amcoupons/checkout/cancelCoupon', array('_secure' => true)) ?>" method="post">
                                <input type="hidden" name="amcoupon_code_cancel" value="<?php echo $this->escapeHtml($coupon); ?>" />
                                <a href="#" onclick="javascript: discountForm.cancel('<?php echo $couponCnt; ?>'); return false;"><?php echo $this->__('Cancel'); ?></a>
                            </form>
                        </td>
                    </tr>
                    <?php $couponCnt++; ?>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>

    <?php endif;?>

</div>

<script type="text/javascript">
    //<![CDATA[
    var discountForm = new VarienForm('discount-coupon-form');
    discountForm.submit = function (isRemove) {
        if (isRemove) {
            $('coupon_code').removeClassName('required-entry');
            $('remove-coupone').value = "1";
        } else {
            $('coupon_code').addClassName('required-entry');
            $('remove-coupone').value = "0";
        }
        return VarienForm.prototype.submit.bind(discountForm)();
    }
    
    discountForm.cancel = function(couponCnt){
        $('discount-coupon-cancel-form-' + couponCnt).submit();
    }
    //]]>
</script>