<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>


<div class="mpblog-page">
    <div class="highlight-post-box">
        <?php if (count($this->getCollection())): ?>
            <?php
            $i = 0;
            foreach ($this->getCollection() as $post): $i++;
                ?>
                <?php if ($i > 1) break; ?>
                <div class="highlight-post">
                    <div class="post-thumbnail">
                        <?php
                        $blogimages = $post->getData('image_top_landing');
                        if($blogimages){
                            ?>
                            <div class="post-thumbnail box-slider">
                                    <img alt="image" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . DS . $blogimages ?>"/>
                            </div>
                        <?php } else{ ?>
                            <img alt="image-default" src="<?php echo $this->getSkinUrl('images/blog/image4.jpg') ?>"/>
                        <?php }?>
                    </div>
                    <a class="mp-post-info" href="<?php echo $post->getPostUrl(); ?>" title="<?php echo $this->__("Read More"); ?>">
                        <label><?php echo $this->escapeHtml($post->getTitle()); ?></label>
                        <span><?php echo $this->__("Read More"); ?></span>
                    </a>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div> 
    <div class="mpblog-container list">
        <div class="mp-blog-head fix-me blog-header">
            <h1 class="mp-title"><?php echo $this->getPageHeader(); ?></h1>
                <div class="mp_blog_menu mobile clearfix">
                  <a id="menu-category-blog" class="icon-menu mobile icon-menu-blog" href="javascript:void(0)"><span>&nbsp;</span><span>&nbsp;</span><span>&nbsp;</span></a>
                  <a id="mobile-blog-search" class="mobile skip-search list" href="#/" title="Search" onclick="showMobileBlogSearch()">
                    <img src="<?php echo $this->getSkinUrl('images/search-magnifier-interface-symbol.png')?>">
                  </a>
                  <div class="block mpblog-search" id="mobile_search" style="display: none;">
                    <div class="block-title">
                      <strong><span><?php echo $this->__("Search the blog") ?></span></strong>
                    </div>
                    <div class="block-content">
                      <form id="mp_blog_search_mobile" action="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getSearchUrl(); ?>" method="get">
                        <div class="input-box">
                          <input type="text" placeholder="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getBlockHeader(); ?>" class="input-text required-entry placeholder" title="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getBlockHeader(); ?>" id="search-blog" name="query" value="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getQuery(); ?>" maxlength="100" />
                        </div>
                        <button class="button" title="<?php echo $this->__("Search"); ?>" type="submit"><span><span><?php echo $this->__("Search"); ?></span></span></button>
                      </form>
                      <script type="text/javascript">
                      //<![CDATA[
                      new VarienForm('mp_blog_search_mobile');
                      //]]>
                      </script>
                    </div>
                  </div>
                </div>  
            <div class="clearfix"></div>
            <div class="wrap-description desktop">  
                <div class="desc_content_cat clearfix">
                <?php if ($this->getCategoryImage($this->getPageHeaderImages())): ?>
                <img class="img-description" src="<?php echo $this->getCategoryImage($this->getPageHeaderImages()); ?>" alt="<?php echo $this->getPageHeader(); ?>">
                <?php endif ?>
                <div class="head_description_cate"><p><?php echo $this->getPageHeaderDescription(); ?></p></div>
                </div>
            </div>
            <a id="menu-category-blog" class="icon-menu desktop icon-menu-blog" href="javascript:void(0)"><span>&nbsp;</span><span>&nbsp;</span><span>&nbsp;</span></a>
             <div class="clearfix"></div>
            <div class="head_description_mobile mobile clearfix">
            <div class="desc_content_cat">
            <?php if ($this->getCategoryImage($this->getPageHeaderImages())): ?>
                <img class="img-description" src="<?php echo $this->getCategoryImage($this->getPageHeaderImages()); ?>" alt="<?php echo $this->getPageHeader(); ?>">
            <?php endif ?>
                <div class="head_description_cate"><p><?php echo $this->getPageHeaderDescription(); ?></p></div>
            </div>
            
            </div>
        </div>
        <div class="block mpblog-search" id="mobile_search" style="display: none;">
            <div class="block-title">
                <strong><span><?php echo $this->__("Search the blog") ?></span></strong>
            </div>
            <div class="block-content">
                <form id="mp_blog_search_mobile" action="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getSearchUrl(); ?>" method="get">
                    <div class="input-box">
                        <input type="text" placeholder="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getBlockHeader(); ?>" class="input-text required-entry placeholder" title="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getBlockHeader(); ?>" id="search-blog" name="query" value="<?php echo Mage::getBlockSingleton('mpblog/sidebar_search')->getQuery(); ?>" maxlength="100" />
                    </div>
                    <button class="button" title="<?php echo $this->__("Search"); ?>" type="submit"><span><span><?php echo $this->__("Search"); ?></span></span></button>
                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    new VarienForm('mp_blog_search_mobile');
                    //]]>
                </script>
            </div>
        </div>
        <div class="blog-header">
            <ul class="blog-tab tab-title">
                <li class="latest-stories active"><a title="<?php echo $this->__('Latest stories') ?>" href="#latest-stories-blog"><span><?php echo $this->__('Latest stories') ?></span></a></li>
                <li class="popular-stories"><a title="<?php echo $this->__('Popular stories') ?>" href="#popular-stories-blog"><span><?php echo $this->__('Popular stories') ?></span></a></li>
            </ul>
        </div>
        <div class="mpblog-list list">
          <div id="list-content-latest">
            <?php echo $this->getChildHtml('list_latest') ?>
          </div>
          <div id="list-content-popular">
            <?php echo $this->getChildHtml('list_popular') ?>
          </div>
        </div>
    </div>
    <div class="mpblog-right">
        <?php echo $this->getChildHtml('sidebar_category'); ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('carnival-blog-sidebar')->toHtml() ?>
    </div>
</div>
<script type="text/javascript">
    jQuery('.icon-menu-blog').on('click', function() {
        if(jQuery(this).hasClass('active')){
            jQuery('.block.mpblog-categories').slideToggle(300);
            jQuery('.icon-menu-blog').removeClass('active');
        }
        else{
            jQuery('.icon-menu-blog').removeClass('active');
            jQuery(this).addClass('active');
            jQuery('.block.mpblog-categories').slideToggle(300);
        }
    });
    function showMobileBlogSearch(){
        var formId = jQuery("#mobile_search");
        if(formId.hasClass('active')){
            formId.removeClass('active');
            formId.hide();
        }
        else{
            formId.addClass('active');
            formId.show();
        }
    }
</script>