<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Common
 */
?>
<?php /** @var $this Magpleasure_Common_Block_Adminhtml_Widget_Form_Snippet  */ ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->htmlEscape($this->getLegend()); ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div id="<?php echo $this->getHtmlId(); ?>" class="fieldset" ng-non-bindable>
        <div class="hor-scroll">
            <script src="//google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
<pre class="<?php echo $this->getSnippetClass(); ?>">
<?php echo $this->getSnippedCodeHtml(); ?>
</pre>
        </div>
    </div>
</div>
