<?php
$templateObject = $this->getDataObject();
$logo = $templateObject->getData('company_logo');
//change by Jack 19/01/2015
$logoUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/logo/' . $logo ;
$logoUrlConverter = Mage::helper('pdfinvoiceplus/product')->convertImage($logoUrl);
//
$name = $templateObject->getData('company_name');
$address = $templateObject->getData('company_address');
$phone = $templateObject->getData('company_telephone');
$email = $templateObject->getData('company_email');
$fax = $templateObject->getData('company_fax');
$businessId = $templateObject->getData('business_id');
$vatnumber = $templateObject->getData('vat_number');
$vatoffice = $templateObject->getData('vat_office');
$note = $templateObject->getData('note');
$term = $templateObject->getData('terms_conditions');
$footer = $templateObject->getData('footer');
$footerHeight = $templateObject->getFooterHeight();
$color = '78C145';
$pageFormat = $templateObject->getFormat();
$barcode_order = $templateObject->getBarcodeInvoice();
$display_images = $templateObject->getDisplayImages();
$orientation = $templateObject->getOrientation();
$font_size_1 = '40px';
$font_size_2 = '14px';
$font_size_3 = '18px';
if ($orientation == 0) {
    if ($pageFormat == 'A5') {
        $font_size_1 = '28px';
        $font_size_2 = '12px';
        $font_size_3 = '14px';
        $title_width = '82%';
        $title_arrow = '10%';
    } else {
        $title_width = '87%';
        $title_arrow = '8%';
    }
} elseif ($orientation == 1) {
    if ($pageFormat == 'A5') {
        $title_width = '84%';
        $title_arrow = '10%';
    } else {
        $title_width = '88%';
        $title_arrow = '7%';
//        $title_width = '91%';
//        $title_arrow = '5%';
    }
}
$barcode = $templateObject->getBarcode();
$barcode_type = $templateObject->getBarcodeType();
//$barcode_value = Mage::helper('pdfinvoiceplus/pdf')->getBarcodeValue();
$status = $templateObject->getStatus();
?>

<style>
    *{margin: 0; padding: 0;}
    body {
        font-size: 12px;
        max-width:100%;
        margin: 0 auto;
        font-family: "Ubuntu Regular", "Ubuntu Light", arial;		
        font-size-adjust: none;
        width: 100%;
    }
    .template02 #container-inner{
        position: relative;
        width: 100%;
        height: auto;
        padding: 0px;
        margin: 0 auto;
        border: 0px;
        word-wrap: normal;
        padding-bottom:<?php echo $footerHeight+10;?>px;
    }
    .template02 .main-content {
        width:90%;
        margin: 0 5% 0;
    }
    .template02 .header-content div span{
        display: block;
        clear:left;
    }
    .template02 p {    margin: 0px;
    }
    
    .template02 table thead th { 
                    background-color: <?php echo '#' . $color; ?>;
                     color: #fff;
                     text-align: center;
                     border: 0.1mm solid #fff;
                     font-weight: bold;
                     padding: 12px 20px;
                     text-transform: uppercase;
    }
    .template02 .table-data tbody td{
        background: #E9E9E9;
        padding: 12px 10px;
        color: #2f2f2f;
        border:1px solid #fff
    }
    .template02 .items td.blanktotal {
        background-color: #FFFFFF;
        border: 0mm none #fff;
        border-top: 0.1mm solid #fff;
        border-right: 0.1mm solid #fff;
    }
    .template02 .items td.totals {
        background: none repeat scroll 0 0 #ffe9d9;
        border: 0 none;
        text-align: right;
        padding: 5px 20px;
    }
    .template02 .top-title span {
        display: block;
        font-size: 15px;
        color: #000;
    }
    .template02 .title-color{
        color: #fff;
        font-size: 14px;
        font-weight: bold;
        text-transform: uppercase;
        padding-left:20px;
        /*float:left;*/
    }

    .template02 .info-cus{
        width: 100%;
        display:inline-block;
    }
    .template02 .content{
        float: left;
        font-size: 14px;
        padding: 12px 20px;
        width: 80%;
    }

    .template02 .shipping-box, .template02 .shipping-add-box{
        float:right;
    }
    .footer-template02{

        background: #E9E9E9;
        margin-top: 50px;
        /*padding-bottom: 10px;*/
        color: #2f2f2f;
        font-size: 14px;
        text-align: left;
        position: absolute;
        bottom:0;
        width:100%;
        display:inline-block;
        border-bottom: 8px solid <?php echo '#' . $color; ?>;;
        /*margin:0 5%;*/
        /*width:90%;*/
        /*left: 5%;*/
    }

    .template02 .bottom-color{
        /*border-top :8px solid <?php echo '#' . $color ?>;*/
        border-bottom :8px solid <?php echo '#' . $color ?>;
    }
    .template02 .table-data tbody td.label{
        color: #2f2f2f;
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 16px;
        /*width:40%;*/
        padding-right: 30%;
    }
    .template02 .table-data tfoot .grand_total td.label strong{                
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 16px;
        line-height: 40px;
    }
    .template02 table.grandtotal td {border:0 none!important; text-align: right!important;}
    /*by viet*/
    .template02 .grand_total {
        color: #bf2323;
        font-size: 16px;
        padding: 5px;
    }
    .template02 .grand_total_value{
        color:#FF6C00;
        font-size:18px;
    }
    .template02 .order-totals{
        width:100%;
        margin-top:50px;
    }

    .template02 .order-grandtotals{
        width:55%; 
        float: right;
        background: #ffe9d9; 

        /*padding:20px;*/
    }
    .template02 .grand-label{
        font-family: 'Ubuntu';
        font-size:16px;
        padding:0px 20px;
    }
    /*            .grand-emph{
                    padding:0px 20px;
                }
                .emph-totals{
                    padding:0px 20px;
                }*/
    .template02 .barcode-order{
        /*margin-top:50px;*/
    }
    
 /*      Zeus 28/01 */   
 <?php 
    
    if($barcode_type == 'QR' && $barcode == 1){
        ?>
   
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/QR.jpg'; ?>") no-repeat;
    }
     <?php
    }
   ?>
    <?php
    if($barcode_type == 'IMB' || $barcode_type == 'RM4SCC' || $barcode_type == 'KIX' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/IMB.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    <?php
    if($barcode_type == 'UPCA' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/UPCA.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN8' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN8.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN128A' || $barcode_type == 'C93' || $barcode_type == 'MSI' || $barcode_type == 'CODABAR' || $barcode_type == 'CODE11' || $barcode_type == 'C39' || $barcode_type == 'S25' || $barcode_type == 'C128A'  && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN128A.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN13' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN13.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'POSTNET' || $barcode_type == 'PLANET' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/POSTNET.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    /*      Zeus 28/01 */   
    
    /*viet*/
    .template02 .totals{
        width:100%;
    }
    .template02 .body-total{
        width:100%;
    }
    .template02 .totals-li{
        width:100%;
        float:left;
        list-style: none outside none;
        padding: 5px 10px;
        color:#333333;
    }
    .template02 .totals-label{
        font-family: 'Ubuntu';
        font-size:16px;
        padding:0px 20px;
        color: #2F2F2F;
        font-weight: bold;
        text-align: right;
        float:left;
        height:20px;
    }
    .template02 .totals-value{
        text-align:right;
        height:20px;
        font-size: 15px;
    }
    .template02 .grand-label{
        color:#000;
    }
    .template02 .term-conditions{
        margin-top:20px;
        margin-bottom:30px;
    }
    .template02 div.arrow{
        height:0px;
        width: 0px;
        border-top: 14px solid transparent;
        border-bottom: 14px solid transparent;
        border-left: 14px solid #78C145;
        border-color: #fff #fff #fff #78C145;
    }
    .template02 div.title{
        background: <?php echo '#' . $color; ?>;
        border-radius: 0 0 0 0;    
        margin-bottom: 0;
        /*height: 14px;*/
/*        padding: 5px 0;*/
        position: relative;
        word-wrap: break-word;
        font-size: 14px;
    }
    /*********************/
    /*Totals*/
    .template02 .totals{
        float: right;
        width: 100%;
        /*            background: #e9e9e9;*/
        margin-bottom: 8px;
    }
    .template02 .body-total{
        height: auto;
        float: right;
        margin: 10px;
    }
    .template02 .total-row{
        width: 100%;
        text-align: right;
        float: right;
        padding: 5pt 0pt;
    }
    .template02 .total-row-grand{ border-top: 1px solid #e9e9e9; }
    .template02 .total-label{
        font-family: 'Ubuntu';
        font-size: 11pt;
        color: #2F2F2F;
        width: 62%;
        float: left;
        height: 22pt;
    }
    .template02 .total-value{
        font-size: 11pt;
        width: 35%;
        height: 22pt;
        float: right;
    }
    .template02 .grand-total, .template02 .grand-total-value, .template02 .grand-total-label {
        font-family: 'Ubuntu';
        font-weight: bold;
        font-size: 12pt;
    }
    .template02 .grand-total-value{
        color: #bf2323;
    }
    /*end totals*/
    /*******************/

    .template02 .note{
        padding: 10px 0;
        float: left;
    }
    .template02 .note-box{
        width: 100%;
        float: left;
    }

    .template02 .term-conditions-box [info-text]{
        clear: left;
        width: 100%;
        padding: 10px 0;
    }   

    /*infomations*/
    .template02 .general-info{ display: block; width:100%; float: left; font-family: 'Ubuntu Light';font-size: <?php echo $font_size_2 ?>; }
    .template02 .general-info .info-label{ font-weight: bold; display: inline-block; }
    .template02 .general-info .info-value{ display: inline-block; }

    .template02 .footer-style{
        display: inline-block;
        margin: 0 5%;
        width: 90%;
    }
</style>
<div id="container-inner" class="template02">
<header name="myheader">
    <div class="color-theme-top" style="width:100%;display: inline-block;background:#E9E9E9;padding-bottom:8px;border-top: 8px solid <?php echo '#' . $color; ?>">
        <div class="header-content" style="float:left;width:90%;margin: 0 5%;">		
            <div style="width: 45%;float: left;">
                <div class='ajaxupload' style="width: 45%; margin-top: 10px;text-align: left; clear: left" info-img="company_logo"><?php echo ($logo) ? '<img width="160" src="' .$logoUrlConverter. '" />' : ''; ?></div>
                <div class="barcode" style="float:left;text-align:left;padding-top:5px">
                        <?php if ($barcode =='1' && $barcode_order): ?>
                            <!--<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/barcode.jpg' ?>">-->
                            <barcode code='<?php echo $barcode_order; ?>' type='<?php echo $barcode_type; ?>' />
                        <?php endif; ?>
                </div>
            </div>
            <div class="autogrow contenteditable"  contextmenu-type="main" contenteditable="true" title="Click to edit, right-click to insert variable" style=" margin-top: 10px; width:45%;color:#000;font-size: 14px;text-align: right; float: right;padding-left:22px">

                <div info-text-outer="company_name" contextmenu-type="main">
                    <?php if ($name): ?>
                        <p class="info-company_name color-text general-info" title="Click to edit, right-click to insert variable" style="font-weight: bold; font-size: <?php echo $font_size_3 ?>; color:#00CC00; text-transform: uppercase;">
                            <span class="color-theme-text info-value" info-text="company_name"><?php echo $name ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_address" contextmenu-type="main">
                    <?php if ($address): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('Add: '); ?> </span>
                            <span class="info-value" info-text="company_address"><?php echo $address ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_email" contextmenu-type="main">
                    <?php if ($email): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('Email: '); ?> </span>
                            <span class="info-value" info-text="company_email"><?php echo $email ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_telephone" contextmenu-type="main">
                    <?php if ($phone): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('Tel: '); ?>  </span>
                            <span class="info-value" info-text="company_telephone"><?php echo $phone ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="company_fax" contextmenu-type="main">
                    <?php if ($fax): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('Fax: '); ?> </span>
                            <span class="info-value" info-text="company_fax"><?php echo $fax ?></span>
                        </p><?php endif; ?></div>
                
                <div info-text-outer="vat_number" contextmenu-type="main">
                    <?php if ($vatnumber): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('VAT Number: ') ?></span>
                            <span class="info-value" info-text="vat_number"><?php echo $vatnumber ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="vat_office" contextmenu-type="main">
                    <?php if ($vatoffice): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('VAT Office: ') ?></span>
                            <span class="info-value" info-text="vat_office"><?php echo $vatoffice ?></span>
                        </p><?php endif; ?></div>
                <div info-text-outer="business_id" contextmenu-type="main">
                    <?php if ($businessId): ?>
                        <p class="color-text general-info" title="Click to edit, right-click to insert variable">
                            <span class="info-label"><?php echo $this->__('Business Id: ') ?></span>
                            <span class="info-value" info-text="business_id"><?php echo $businessId ?></span>
                        </p><?php endif; ?></div>

            </div>
            
        </div>
    </div>
</header>
<div id="main-content" class="main-content">
    <div class="top-title" style="width: 100%;clear: both;padding-bottom: 5px;">
        <div style="float:left;width:50%">
            <div style="width:100%;float:left"  contextmenu-type="main">
            <div class="color-theme-text contenteditable" contenteditable="true" title="Click to edit, right-click to insert variable"  style="color: <?php echo '#' . $color; ?>; font-family: 'Ubuntu Regular';text-align:left; font-size: <?php echo $font_size_1 ?>;font-weight: normal; text-transform: uppercase;"><?php echo $this->_locale->translate('Invoice'); ?></div>
            <?php if ($status): ?><span class="color-text contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" style="display: block;width:100%;float: left; padding-top:0px;padding-bottom:20px"><strong><?php echo $this->__('Status:') ?> </strong>{{var invoice_state}}</span><br/><?php endif; ?>
            </div>
        </div>
        <div  style="float:left;width: 50%;">
            <div style="text-align: right;float:right;"  contextmenu-type="main" class="content contenteditable">
                <span class="color-text contenteditable" contenteditable="true" title="Click to edit, right-click to insert variable" style="font-family: 'Ubuntu Medium';font-size: 26px;">#{{var invoice_increment_id}}</span><br/>
                <span class="color-text contenteditable" contenteditable="true" title="Click to edit, right-click to insert variable" style="color: #010101;font-size: 18px;">{{var invoice_created_at}}</span>
            </div>
        </div>
        
    </div>
    <div class="info-cus">				
        <div style="width:49%;float:left" class="billing-box">
            <div style="width:100%">
                <div class="title"   style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Billing Address') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true"  contextmenu-type="main" title="Click to edit, right-click to insert variable" class="content contenteditable">
                <address >{{var invoice_billing_address}}</address>
            </div>
        </div>

        <div style="width:49%;float:right;margin-left: 0" class="shipping-add-box">
            <div style="width:100%">
                <div class="title"   style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Shipping Address') ?></div>
                </div>
                <div class="arrow" style="width:<?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true"  contextmenu-type="main" title="Click to edit, right-click to insert variable" class="content contenteditable">
                <address >{{var invoice_shipping_address}}</address>
            </div>
        </div>		
    </div>

    <div style="padding-bottom: 5px;" class="">		
        <div style="width:49%;float:left;" class="payment-box">
            <div style="width:100%">
                <div class="title"   style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Payment Method') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>				
            <div class="content contenteditable" contextmenu-type="main" title="Click to edit, right-click to insert variable" contenteditable="true">
                {{var invoice_payment_method}}
            </div>
        </div>

        <div style="width:49%;float:right;" class="shipping-box">
            <div style="width:100%">
                <div class="title"  style="width:<?php echo $title_width; ?>;float:left;height: 28px;">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable" style="padding:0 20px;line-height: 28px;">
                        <?php echo $this->_locale->translate('Shipping Method') ?></div>
                </div>
                <div class="arrow" style="width: <?php echo $title_arrow; ?>; float: left;"></div>
            </div>
            <div contenteditable="true" contextmenu-type="main" title="Click to edit, right-click to insert variable" class="content contenteditable">
                {{var invoice_shipping_method}}
            </div>
        </div>		
    </div>

    <!--<h3 style="font-size: 12pt; color: rgb(47, 79, 78);  text-transform: uppercase;font-weight:bold">Ordered Items</h3>-->
    <table id="table-item" class="items table-data" width="100%" style="font-size: 14px; border-collapse: collapse;" cellpadding="6">
        <thead>
            <tr>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="25%" style="font-family:'Ubuntu';text-align:left;"><?php echo $this->_locale->translate('Product'); ?></th>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('SKU') ?></th>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Price') ?></th>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Qty') ?></th>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Tax') ?></th>
                <th class="color-theme label contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php echo $this->_locale->translate('Subtotal') ?></th>
<!--                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php //echo $this->_locale->translate('Tax') ?></th>
                <th class="color-theme label" contenteditable="true" width="auto" style="font-family:'Ubuntu';text-align:right;"><?php //echo $this->_locale->translate('Discount') ?></th>
                <th class="color-theme label" contenteditable="true" width="10%" style="font-family:'Ubuntu';text-align:right;"><?php //echo $this->_locale->translate('Row Total') ?></th>-->
            </tr>
        </thead>
        <tbody>
            <!-- ITEMS HERE -->
            <!--            ##productlist_start##-->
            <tr>
                <td class="color-text background-items contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="left">{{var items_name}}<br/>{{var items_product_options}}</td>
                <td class="color-text background-items contenteditables" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_sku}}</td>
                <td class="color-text background-items contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_price}}</td>
                <td class="color-text background-items contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_qty}}</td>
                <td class="color-text background-items contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_tax_amount}}</td>
                <td class="color-text background-items contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>
<!--                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_tax_amount}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_discount_amount}}</td>
                <td class="color-text" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>-->
            </tr>
            <!--            ##productlist_end##-->
        </tbody>        
    </table>
    <div class="after-item" style="width:100%;display:inline-block;margin-top:10px">
        <div class="totals autogrow contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="main" contenteditable="true">
            <div class="body-total" title="Click to edit, right-click to insert variable">
                <div class="total-row" contextmenu-type="main">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Subtotal'); ?></div>
                    <div class="total-value color-text">{{var invoice_subtotal}}</div>
                </div>
                <div class="total-row" contextmenu-type="main">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Tax'); ?></div>
                    <div class="total-value color-text">{{var invoice_tax_amount}}</div>
                </div>
                <div class="total-row" contextmenu-type="main">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Shipping'); ?></div>
                    <div class="total-value color-text">{{var invoice_shipping_amount}}</div>
                </div>
                <div class="total-row total-row-grand" contextmenu-type="main">
                    <div class="total-label color-text grand-total"><?php echo $this->_locale->translate('Grand Total'); ?></div>
                    <div class="total-value color-text grand-total grand-total-value">{{var invoice_grand_total}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="note-box">
        <?php if ($note): ?>
            <div title="Click to edit, right-click to insert variable" class="note color-text contenteditable" contenteditable="true" style="" contextmenu-type="main" info-text="note"><?php echo $note; ?></div>
        <?php endif; ?>
    </div>

    <div class="term-conditions term-conditions-box">
        <?php if ($term): ?>
            <p title="Click to edit, right-click to insert variable" class="color-text contenteditable" style="" contextmenu-type="main" contenteditable="true" info-text="terms_conditions"><?php echo $term; ?></p>
        <?php endif; ?>
    </div>
</div>
</div>

<!--        <div id="footer" contextmenu-type="main" class="footer  autogrow color-text" name="myfooter" >
            <div contenteditable="true" class="footer-text bottom-color" style="padding-top: 10px;width: 100%;padding-left: 5%;" info-text="footer">-->
    <div id="footer" contextmenu-type="main" style="height: <?php echo $footerHeight;?>px;" title="Click to edit, right-click to insert variable" class="footer-template02 color-theme-bottom contenteditable" contenteditable="true" name="myfooter" >
        <div class="color-text footer-style" style="padding-top: 10px; display:inline-block;" info-text="footer"><?php if ($footer) echo $footer; ?></div>
    </div>
    <script type="text/javascript">
//    $(function() {
//        if ($('#footer').length > 0) {
//            var footer = $('#footer').height()+40;
//            $('#container-inner').css('padding-bottom', footer + 'px');
//        }
//    });
    </script>
