<div id="login">
<!--	<div id="registered_login">-->
<!--		<p class="mastercheckout-login-title"><a class="mastercheckout-login-link" title="" href="--><?php //echo $this->getUrl('customer/account/login')?><!--">--><?php //echo $this->__('Already registered? Click here to login.')?><!--</a></p>-->
<!--	</div>-->
	<input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
</div>