<?php if($this->isCustomerLoggedIn()): ?>
  <h3 class="mastercheckout-title"><?php echo $this->__('My addresses') ?></h3>
<?php endif ?>
<form action="" id="co-shipping-form">
  <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
      <li class="wide">
        <label class="label-title" for="shipping-address-select">
          <?php echo $this->__('Shipping') ?>
          <a href="javascript:void(0)" class="a-edit" onclick="editShippingAddress();"><?php echo $this->__('Edit'); ?></a>
        </label>
        <div class="input-box">
          <?php $shippingAddressDefault = $this->getDefaultInputShippingaddress(); ?>
          <?php $addresses = $this->getShippingaddresses(); ?>
          <div id="shipping-addresses" class="custom-select-style1">
            <input type="hidden" id="shipping-address-input-choosed" name="shipping_address_id" value="<?php echo $shippingAddressDefault['address_id']; ?>" class="">
            <label id="shipping-address-input" class="address-select"><?php echo $shippingAddressDefault['address_html']; ?></label>

            <button type="button" id="show-list-shipping-address" class="show-list-address"><span><?php echo $this->__('List addresses')?></span></button>
            <ul class="select-one-option" id="shipping-address-select-option">
              <li id="option-new-address">
                <label address_id="new" onclick="changeShippingAddress(this);"><span><?php echo $this->__('New address'); ?></span></label>
              </li>
              <li>
                <ul class="customer-list-address-checkout">
                  <?php foreach ($addresses as $address): ?>
                    <li>
                      <label id="shipping-lablel-<?php echo ($address->getId()); ?>" address_id="<?php echo ($address->getId()); ?>" onclick="changeShippingAddress(this);"><?php echo ($address->format('oneline')); ?></label>
                      <input type="hidden" id="shipping_address_hidden_<?php echo $address->getId(); ?>" country_id ="<?php echo $address->getCountryId()?>"
                             shipping_firstname="<?php echo $address->getFirstname() ?>" shipping_lastname="<?php echo $address->getLastname() ?>"
                             shipping_street="<?php echo $address->getStreet(1) ?>" shipping_regionId ="<?php echo $address->getRegionId() ?>"
                             shipping_cityId="<?php echo $address->getCityId() ?>" shipping_subdistrictId ="<?php echo $address->getSubdistrictId() ?>"
                             shipping_postcode="<?php echo $address->getPostcode() ?>" shipping_telephone="<?php echo $address->getTelephone() ?>"
                             shipping_region = "<?php echo $address->getRegion() ?>" shipping_city ="<?php echo $address->getCity() ?>"
                             shipping_subdistrict ="<?php echo $address->getSubdistrict() ?>"
                        >
                    </li>
                  <?php endforeach; ?>
                </ul>
              </li>
            </ul>
          </div>
          <script type="text/javascript">
            jQuery(document).ready(function(){
              jQuery('#shipping-addresses .show-list-address').click(function () {
                if (!jQuery(this).hasClass('active')) {
                  jQuery(this).next('ul').slideDown(300);
                  jQuery(this).addClass('active');
                  $j('#shipping-address-select-option').mCustomScrollbar();
                }
                else if (jQuery(this).hasClass('active')) {
                  jQuery(this).next('ul').slideUp(300);
                  jQuery(this).removeClass('active');
                }
              });
            });
          </script>
        </div>
      </li>
    <?php else: ?>
      <ul class="form-list">
        <li class="wide">
          <label class="label-title" for="shipping-address-select">
            <?php echo $this->__('shipping') ?>
          </label>
        </li>
      </ul>
    <?php endif; ?>
    <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>

      <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
      <ul>
        <li class="fields show-label"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
        <li class="fields">
          <?php if (Mage::getStoreConfig('mastercheckout/adressoptions/company')) {?>
            <div class="fields">
              <label for="shipping:company"><?php echo $this->__('Company') ?></label>
              <div class="input-box">
                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" onchange="shipping.setSameAsBilling(false);" />
              </div>
            </div>
          <?php }?>
        </li>
        <li class="fields">
          <?php if(!$this->isCustomerLoggedIn()): ?>
        <li class="fields">
          <div class="fields">
            <label for="shipping:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
              <input type="text" name="shipping[email]" id="shipping:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
            </div>
          </div>
        </li>
        <?php endif ?>
    </li>
    <li class="wide">
      <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address (Please fill in complete data)') ?></label>
      <div class="input-box">
        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" onchange="shipping.setSameAsBilling(false);" />
      </div>
    </li>
    <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
      <li class="wide">
        <div class="input-box">
          <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text" onchange="shipping.setSameAsBilling(false);" />
        </div>
      </li>
    <?php endfor ?>
    <li class="fields">
      <div class="field">
        <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
        <div class="input-box">
          <?php echo $this->getCountryHtmlSelect('shipping') ?>
        </div>
      </div>
    </li>
    <li class="fields">
      <div id="mastercheckout_shipping_region" class="field">
        <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
        <div class="input-box">
          <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
          </select>
          <script type="text/javascript">
            //<![CDATA[
            $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
            //]]>
          </script>
          <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
        </div>
      </div>
      <div class="field">
        <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
        <div class="input-box">
          <select id="shipping:city_id" name="shipping[city_id]" title="<?php echo $this->__('City') ?>" class="validate-select" style="display:none;">
            <option value=""><?php echo $this->__('Please select City') ?></option>
          </select>
          <script type="text/javascript">
            //<![CDATA[
            $('shipping:city_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getCityId() ?>");
            //]]>
          </script>
          <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
        </div>
      </div>
      <div class="field">
        <label for="shipping:subdistrict" class="required"><em>*</em><?php echo $this->__('Subdistrict') ?></label>
        <div class="input-box">
          <select id="shipping:subdistrict_id" name="shipping[subdistrict_id]" title="<?php echo $this->__('Subdistrict') ?>" class="validate-select" style="display:none;">
            <option value=""><?php echo $this->__('Please select Subdistrict') ?></option>
          </select>
          <script type="text/javascript">
            //<![CDATA[
            $('shipping:subdistrict_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getSubdistrictId() ?>");
            //]]>
          </script>
          <input type="text" name="shipping[subdistrict]" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subdistrict')) ?>" class="input-text" id="shipping:subdistrict" />
        </div>
      </div>
    </li>
    <li class="fields">
      <div class="field">
        <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
        <div class="input-box">
          <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" onchange="shipping.setSameAsBilling(false);" />
        </div>
      </div>
    </li>
    <li class="fields">
      <div class="field">
        <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
        <div class="input-box">
          <input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
        </div>
      </div>
    </li>
    <li class="fields">
      <?php if (Mage::getStoreConfig('mastercheckout/adressoptions/fax')) {?>
        <div class="field">
          <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
          <div class="input-box">
            <input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
          </div>
        </div>
      <?php }?>
    </li>
    <?php if(!$this->isCustomerLoggedIn()): ?>
      <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
      <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
      <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
        <li class="fields">
          <?php if ($_dob->isEnabled()): ?>
            <div class="field">
              <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>
            </div>
          <?php endif; ?>
          <?php if ($_gender->isEnabled()): ?>
            <div class="field">
              <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>
            </div>
          <?php endif ?>
        </li>
      <?php endif ?>

      <?php if ($this->isTaxvatEnabled()):?>
        <li><?php echo $this->getTaxvatHtml() ?></li>
      <?php endif; ?>

      <li class="fields" id="register-customer-password">
        <div class="field">
          <label for="shipping:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
          <div class="input-box">
            <input type="password" name="shipping[customer_password]" id="shipping:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
          </div>
        </div>
        <div class="field">
          <label for="shipping:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
          <div class="input-box">
            <input type="password" name="shipping[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="shipping:confirm_password" class="input-text required-entry validate-cpassword" />
          </div>
        </div>
      </li>
      <li class="control mastercheckout-checkbox" <?php echo (Mage::getStoreConfig('mastercheckout/adressoptions/subscribenewsletter') == "0")?' style="display:none !important;"':''; ?>>
        <div class="input-box">
          <input id="shipping:is_subscribed" class="checkbox" type="checkbox" value="1" title="<?php echo $this->__("Sign Up for Newsletter")?>" name="shipping[is_subscribed]"/>
        </div>
        <label for="shipping:is_subscribed"><?php echo $this->__("Sign Up for Newsletter")?></label>
      </li>
      <?php echo $this->getChildHtml('persistent.remember.me'); ?>
    <?php endif; ?>
    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
      <li class="control">
        <div class="control">
          <button type="button" title="<?php echo $this->__('Save'); ?>" class="button" onclick="saveToAddressBook('shipping');">
            <span><span><?php echo $this->__('Save'); ?></span></span>
          </button>
        </div>
      </li>
    <?php endif;?>
    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
      <li class="control mastercheckout-checkbox" style="display: none !important;">
        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
    <?php else:?>
      <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
    <?php endif;?>
  </ul>

  </li>
  <li class="control" style="display:none">
    <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
  </li>
  </ul>
  <div id="shipping-buttons-container">
    <!--        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>-->
    <!--<span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php /*echo $this->getSkinUrl('images/opc-ajax-loader.gif') */?>" alt="<?php /*echo $this->__('Loading next step...') */?>" title="<?php /*echo $this->__('Loading next step...') */?>" class="v-middle" /> <?php /*echo $this->__('Loading next step...') */?>
        </span>-->
  </div>
</form>
<script type="text/javascript">
  //<![CDATA[
  jQuery("#shipping\\:country_id").val("<?php echo Mage::getStoreConfig('mastercheckout/maingroup/country'); ?>");
  jQuery(document).ready(function(){
    hideState();
    jQuery("#shipping\\:country_id").change(function(event){
//            console.log(jQuery("#billing\\:region_id").css("display"));
//            console.log("<?php echo Mage::getStoreConfig('mastercheckout/adressoptions/region')?>");
      hideState();
    });
    function hideState(){
      if (jQuery("#shipping\\:region_id").css("display") == "none" && <?php echo Mage::getStoreConfig('mastercheckout/adressoptions/region')?> == "0") {
        Element.hide('mastercheckout_shipping_region');
      } else {
        Element.show('mastercheckout_shipping_region');
      }
    }
  });

  var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
  var shippingCityUpdater = new CityUpdater('shipping:country_id', 'shipping:region_id', 'shipping:city', 'shipping:city_id', <?php echo Mage::helper('customaddress')->getCityJson() ?>);

  var shippingSubdistrictUpdater = new SubdistrictUpdater('shipping:country_id', 'shipping:region_id', 'shipping:city_id', 'shipping:subdistrict', 'shipping:subdistrict_id', 'shipping:postcode', <?php echo Mage::helper('customaddress')->getSubdistrictJson() ?>);

  function changeShippingAddress(element){
    if(element.getAttribute('address_id')){
      var addressId = element.getAttribute('address_id');
      if(addressId == 'new'){
        $('shipping-address-input').update(element.textContent);
        $('shipping-address-input-choosed').value = 'new';
        $('shipping-new-address-form').show();
      }
      else{
        $('shipping-address-input').update(element.textContent);
        $('shipping-address-input-choosed').value = addressId;
        $('shipping-new-address-form').hide();
      }
      $('shipping-address-select-option').hide();
      $('show-list-shipping-address').removeClassName('active');
    }
  }

  function editShippingAddress(){
    $('shipping-new-address-form').show();
    var shippingChoosedAddressId = $('shipping-address-input-choosed').value;

    //update form edit shipping address
    if(shippingChoosedAddressId != 'new'){
      $('shipping:firstname').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_firstname');
      $('shipping:lastname').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_lastname');
      $('shipping:street1').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_street');
      $('shipping:region_id').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_regionId');
      $('shipping:region').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_region');
      $('shipping:country_id').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('country_id');
      $('shipping:city_id').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_cityId');
      $('shipping:city').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_city');

      $('shipping:subdistrict_id').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_subdistrictId');
      $('shipping:subdistrict').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_subdistrict');
      $('shipping:postcode').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_postcode');
      $('shipping:telephone').value = $('shipping_address_hidden_'+shippingChoosedAddressId).getAttribute('shipping_telephone');
      shippingRegionUpdater.update()
      shippingCityUpdater.update();
      shippingSubdistrictUpdater.update();
    }
  }
  //]]>
  //]]>
</script>