<?php $_code = $this->getMethodCode(); ?>
<?php ?>

<script type="text/javascript">
    jQuery(document).ready(function() {

        //case if customer login
        jQuery("#card_form_2c2p_gateway").hide();
        if(jQuery("#new_2c2p_card").length === 0)
        {
            jQuery("#card_form_2c2p_gateway").show();

        }


        $j('input[type=radio][name="payment[custom_field_one]"]').on('change', function () {
            jQuery("#card_form_2c2p_gateway").hide();

            // $('list-omise-card').hide();
            switch ($j(this).val()) {
                case 'new_2c2p_card':
                    jQuery('#card_form_2c2p_gateway').show();
                    break;
                case 'transfer':
                    break;
            }
        });

    });




</script>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style='display:none;'>
    <?php
    if(Mage::getSingleton('customer/session')->isLoggedIn()){
        $stored_card  = Mage::getStoreConfig('payment/p2c2p/stored_card', Mage::app()->getStore());

            $customer_id = Mage::getSingleton('customer/session')->getId();

            $p2c2pTokenModel = Mage::getModel('p2c2p/token');

            if(!$p2c2pTokenModel) {
                die("2C2P Expected Model not available.");
            }

            $customer_data = $p2c2pTokenModel->getCollection()->addFieldToFilter('user_id',$customer_id);
            $strHtml = '';?>
            <li id="list-2c2p-card" class="list-2c2p-card">
                <!--<h6 class=""><?php /*echo $this->__('Your existed card') */ ?></h6>-->
                <ul>
                    <?php foreach ($customer_data as $key => $value): ?>
                        <li class="control <?php echo $value->getData('payment_scheme') ?>">
                            <input type="radio"  name="payment[custom_field_one]"  id="<?php echo $value->getData('p2c2p_id') ?>"
                                   value="<?php echo $value->getData('p2c2p_id') ?>"
                                   <?php if ($value->getData('is_default') == 1): ?>checked="checked"<?php endif; ?>
                                   class="radio validate-one-required-by-name"/><label
                                    for="<?php echo $value->getData('p2c2p_id')?>">
                                    <?php if($value->getData('payment_scheme')=='VI')
                                            {
                                                $cardlogo ='images/icon-payment/logo-visa.png';
                                            }
                                            elseif ($value->getData('payment_scheme')=='MA') {
                                                 $cardlogo ='images/icon-payment/logo-master.png';
                                             }
                                            elseif ($value->getData('payment_scheme')=='JC') {
                                                 $cardlogo ='images/icon-payment/logo-jcb.png';
                                             }
                                             else
                                             {
                                                $cardlogo ='images/icon-payment/logo-visa.png';
                                             }  
                                        ?>
                                        <img class="logo-card-2" src="<?php echo $this->getSkinUrl($cardlogo) ?> ">
                                    <span><?php echo  $value->getData('masked_pan') ?></span>
                            </label>
                        </li>
                    <?php endforeach; ?>
                    <li class="control new-card">
                        <input type="radio" name="payment[custom_field_one]" id="new_2c2p_card" value="new_2c2p_card"
                               class="radio validate-one-required-by-name"/><label
                                for="new_2c2p_card">
                            <span><?php echo $this->__('Add new credit/debit card') ?></span></label>
                    </li>
                </ul>
            </li>

        <?php   } ?>

    <ul class="form-list p2c2p_new_card_form" id="card_form_2c2p_gateway">
        <li class="fields">
            <label for="<?php echo $_code ?>_cc_type_card"
                   class="required"><em>*</em><?php echo $this->__('Please select card type') ?></label>
            <div class="input-box">
                <select autocomplete="off"
                        id="<?php echo $_code ?>_cc_type_card" name="card_type" class="required-entry">
                    <option value="credit_card"><?php echo $this->__('Credit Card') ?></option>
                    <option value="debit_card"><?php echo $this->__('Debit Card') ?></option>
                </select>
            </div>
        </li>
        <li class="fields">
            <label for="<?php echo $_code ?>_cc_number"
                   class="required"><em>*</em><?php echo $this->__('Card number') ?></label>
            <div class="input-box">
                <input type="text" maxlength="16" autocomplete="off" data-encrypt="cardnumber"
                       class="input-text required-entry validate-cc-number validate-cc-type required"
                       id="<?php echo $_code ?>_cc_number"
                       title="<?php echo $this->__('Card number') ?>" value=""/>
            </div>
        </li>

        <li class="fields">
            <label for="<?php echo $_code ?>_cc_owner"
                   class="required"><em>*</em><?php echo $this->__('Cardholder Name'); ?>
            </label>
            <div class="input-box">
                <input type="text" name="holder_name" data-2c2p="holder_name" id="<?php echo $_code ?>_cc_name"
                       class="input-text required-entry"
                       title="<?php echo $this->__('Cardholder Name') ?>"
                />
            </div>
        </li>
        <li class="omise-sub-info">
            <ul>
                <li id="p2c2p_gateway_cc_type_exp_div" class="2c2p-exp-date">
                    <label for="<?php echo $_code ?>_expiration"
                           class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select class="input-text required-entry" data-encrypt="month" id="<?php echo $_code ?>_expiration">
                                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select class="input-text required-entry"  data-encrypt="year" id="<?php echo $_code ?>_expiration_yr">
                                <?php foreach ($this->getCcYears() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="fields" id="p2c2p_gateway_cc_type_cvv_div">
                    <label for="<?php echo $_code ?>_cc_cid"
                           class="required"><em>*</em><?php echo $this->__('CVV') ?></label>
                    <div class="input-box">
                        <div class="input-box">
                            <div class="v-fix">
                                <input autocomplete="off" data-encrypt="cvv"
                                       type="text"
                                       title="<?php echo $this->__('CVV') ?>"
                                       class="input-text cvv required-entry validate-cc-cvn"
                                       id="<?php echo $_code ?>_cc_cid"
                                       value=""/>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </li>

        <li>
            <div class="control">
                <input type="checkbox" value="1" name="payment[is_saved_card]" id="customer-card-detail"
                       class="checkbox"/>
                <label for="customer-card-detail"><?php echo $this->__('Save Card') ?><p class="raffle-save-card"><?php echo $this->__('Information is encrypted and securely stored') ?></label>
            </div>
            <div class="control">
                <input type="checkbox" value="1" name="payment[accept_term]" id="accept_term"
                       class="required-entry checkbox"/>
                <label for="accept_term"><?php echo $this->__('Accept Term & Condition') ?></label>
            </div>
        </li>
    </ul>
    <?php         $test_mode = Mage::getStoreConfig('payment/p2c2p/gatewayurl', Mage::app()->getStore());
    if($test_mode):
        ?>
        <script type="text/javascript" src="https://demo2.2c2p.com/2C2PFrontEnd/SecurePayment/api/my2c2p.1.6.9.min.js"></script>
    <?php else: ?>
        <script type="text/javascript" src="https://t.2c2p.com/securepayment/api/my2c2p.1.6.9.min.js"></script>
    <?php endif; ?>
</div>
