<?php
$templateObject = $this->getDataObject();
$logo = $templateObject->getData('company_logo');
//change by Jack 19/01/2015
$logoUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/logo/' . $logo ;
$logoUrlConverter = Mage::helper('pdfinvoiceplus/product')->convertImage($logoUrl);
//
$name = $templateObject->getData('company_name');
$address = $templateObject->getData('company_address');
$phone = $templateObject->getData('company_telephone');
$email = $templateObject->getData('company_email');
$fax = $templateObject->getData('company_fax');
$businessId = $templateObject->getData('business_id');
$vatnumber = $templateObject->getData('vat_number');
$vatoffice = $templateObject->getData('vat_office');
$note = $templateObject->getData('note');
$footer = $templateObject->getData('footer');
$footerHeight = $templateObject->getFooterHeight();
$color = 'ff6c00';
$pageFormat = $templateObject->getFormat();
$barcode_order = $templateObject->getBarcodeCreditmemo();
$display_images = $templateObject->getDisplayImages();
$orientation = $templateObject->getOrientation();
if ($orientation == 0) {
    if ($pageFormat == 'A5') {
        $title_width = '83%';
    } else {
        $title_width = '90%';
    }
} elseif ($orientation == 1) {
    if ($pageFormat == 'A5') {
        $title_width = '88.5%';
    } else {
        $title_width = '93%';
    }
}
$barcode = $templateObject->getBarcode();
$barcode_type = $templateObject->getBarcodeType();
//$barcode_value = Mage::helper('pdfinvoiceplus/pdf')->getBarcodeValue();
$term = $templateObject->getTermsConditions();
$status = $templateObject->getStatus();
?>
<style>
    *{
        margin: 0;
        padding: 0;
    }
    body {
        font-size: 12px;
        max-width:542px;
        margin: 0 auto;
    }
    .template06 .main-content {
        max-width:542px;
        margin: 0 auto 0;
    }
   .template06  .info-cus{
        float: left;
        width: 100%;
    }
   .template06  .comment-box{
        float: left;
        margin-bottom: 10px;
    }
   .template06  .comment-box .content{
        float: left;
        font-size: 12px;
    }
   .template06  div.title{
        margin-bottom: 0;
        position: relative;
        word-wrap: break-word;
        font-size: 14px;
        text-transform:uppercase;
    }
    .template06 .comment-box.shipping-box, .template06  .comment-box.shipping-add-box{
        /*margin-left: 10px;*/
    }
   .template06  .title-color{
        padding: 5px 0px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted.png' ?>);
    }
   .template06  .top-title{
        padding: 5px 0px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted2.png' ?>);
    }
   .template06  .top-table{
        padding: 5px 0px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted.png' ?>);
    }
    .template06 .bottom-table{
        padding: 5px 0px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted2.png' ?>);
    }
    .template06 .note-box {
        float: left;
        width: 100%;
    }
    .template06 .note{
        padding: 5px 0px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted2.png' ?>);
    }
    .footer-template06{
        background: #fff;
        /*padding-bottom: 10px;*/
        color: #2f2f2f;
        font-size: 12px;
        text-align: left;
        position:absolute;
        left: 0;
        bottom:0;
        /*margin: 10px;*/
        padding: 10px 3%;
        width:94%;
    }
    .template06 .footer-text{
        background-repeat: repeat-x;
        background-position:top;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted.png' ?>);
    }
    /*********************/
    /*Totals*/
    .template06 .body-total{
        width: 100%;
        height: auto;
        float: left;
        padding: 10px 0px;
        font-size:12px;
        padding-bottom:5px;
        background-repeat: repeat-x;
        background-position:bottom;
        background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/design/images/dotted.png' ?>);
    }
   .template06  .total-row{
        width: 100%;
        text-align: right;
        padding: 2pt 0pt;
    }
   .template06  .total-row-grand{ text-transform: uppercase; font-weight:bold; }
   .template06  .total-label{
        width: 40%;
        float: left;
    }
    .template06 .total-value{
        width: 55%;
        float: right;
    }
    /*end totals*/
    /*******************/
    .template06 .barcode{
        text-align:center;
/*        clear:left;*/
        padding-bottom:5px;
    }
    
    /*      Zeus 28/01 */   
 <?php 
    
    if($barcode_type == 'QR' && $barcode == 1){
        ?>
   
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/QR.jpg'; ?>") no-repeat;
    }
     <?php
    }
   ?>
    <?php
    if($barcode_type == 'IMB' || $barcode_type == 'RM4SCC' || $barcode_type == 'KIX' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/IMB.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    <?php
    if($barcode_type == 'UPCA' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/UPCA.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN8' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN8.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN128A' || $barcode_type == 'C93' || $barcode_type == 'MSI' || $barcode_type == 'CODABAR' || $barcode_type == 'CODE11' || $barcode_type == 'C39' || $barcode_type == 'S25' || $barcode_type == 'C128A'  && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN128A.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'EAN13' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    width: 160px;
    margin:auto;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/EAN13.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    <?php
    if($barcode_type == 'POSTNET' || $barcode_type == 'PLANET' && $barcode == 1){
        ?>
    .barcode:before {
    content: "";
    display: block;
    margin:auto;
    width: 160px;
    height: 100px;
    background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'magestore/pdfinvoiceplus/barcode/POSTNET.jpg'; ?>") no-repeat;
    }
    <?php
    }
    ?>
    
    /*      Zeus 28/01 */   
    
    /*end barcode*/
    #container-a6{
        display:inline-block;
        padding-left:3%;
        padding-right:3%;
        padding-bottom:<?php echo $footerHeight+20;?>px;
    }
</style>
<div id="container-a6" class="template06">
    <header name="myheader">
        <div contextmenu-type="main" class="header-content" style="width:100%; float: left; margin: 0 auto;">		
            <div class="address contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" style=" width:100%; color:#000;font-size: 14px;text-align: center; float: left;">
                <span style="font-weight: bold; font-size: 16px; text-transform: uppercase;text-align:center" info-text="company_name">
                    <?php if ($name): ?><?php echo $name ?><?php endif; ?>
                </span><br/>
                <span style="font-size: 14px;text-align: center;" info-text="company_address">
                    <?php if ($address): ?><?php echo $address ?><?php endif; ?>
                </span>
            </div>

        </div>
    </header>
    <div id="main-content" class="main-content">
        <div class="top-title" style="display:inline-table; width: 100%;clear: both;">
            <div style="text-align:center">
                <div contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" style="font-family: 'Ubuntu Regular';text-align:center; font-size: 14px;font-weight: normal; text-transform: uppercase;"><?php echo $this->_locale->translate('Credit memo'); ?></div>
                <span contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" style="font-family: 'Ubuntu Medium';font-size: 14px;">#{{var creditmemo_increment_id}}</span>
            </div>
            <div style="text-align: center;vertical-align: middle;">
                <span contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable" style="color: #010101;font-size: 16px;" contenteditable="true">{{var creditmemo_created_at}}</span>
            </div>
            <div class="barcode" >
                <?php if ($barcode_order && $barcode =='1'): ?>
                    <barcode code='<?php echo $barcode_order; ?>' type='<?php echo $barcode_type; ?>' />
                <?php endif; ?>
            </div>
        </div>
        <div class="info-cus">				
            <div style="width:50%" class="billing-box comment-box">
                <div class="title">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable">
                        <?php echo $this->_locale->translate('Billing Address') ?>
                    </div>
                </div>
                
                    <address contextmenu-type="main" contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true">{{var creditmemo_billing_address}}</address>
               
            </div>

            <div style="width:50%" class="shipping-add-box comment-box">
                <div class="title">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable">
                        <?php echo $this->_locale->translate('Shipping Address') ?>
                    </div>
                </div>
                <address contextmenu-type="main" contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true">{{var creditmemo_shipping_address}}</address>
            </div>		
        </div>


        <div style="margin-bottom: 5px;" class="info-cus">		
            <div style="width:50%" class="payment-box comment-box">
                <div class="title">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable"><?php echo $this->_locale->translate('Payment Method') ?></div>
                </div>				
                
                    <div contextmenu-type="main" contextmenu-type="main" class="contenteditable" title="Click to edit, right-click to insert variable"  contenteditable="true">
                        {{var creditmemo_payment_method}}
                    </div>
               
            </div>

            <div style="width:50%" class="shipping-box comment-box">
                <div class="title">
                    <div contenteditable="true" title="Click to edit, right-click to insert variable" class="title-color contenteditable"><?php echo $this->_locale->translate('Shipping Method') ?></div>
                </div>
                
                    <div contextmenu-type="main" contextmenu-type="main" contenteditable="true" title="Click to edit, right-click to insert variable" class="contenteditable">
                        {{var creditmemo_shipping_method}}
                    </div>
                
            </div>		
        </div>

        <!--<h3 style="font-size: 12pt; color: rgb(47, 79, 78);  text-transform: uppercase;font-weight:bold">Ordered Items</h3>-->
        <!-- produc items -->

        <div>
            <div class="top-table contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true">
                <span style="text-transform:uppercase;font-weight:bold; color:#ffffff; "><?php echo $this->_locale->translate('Items'); ?></span>
            </div>
            <table class="items table-data" title="Click to edit, right-click to insert variable" width="100%" style="font-size: 12px; border-collapse: collapse;margin-bottom: 10px;" cellpadding="6">
                <div class="top-table contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true">
                <span style="text-transform:uppercase;font-weight:bold;"><?php echo $this->_locale->translate('Items'); ?></span>
            </div>
                <thead>
                    <tr>
                        <th class="contenteditable" contenteditable="true" width="13%" style="font-family:'Ubuntu';text-align: center"></th>
                        <th class="contenteditable" contenteditable="true" width="15%" style="font-family:'Ubuntu';text-align:center;"></th>
                        <th class="contenteditable" contenteditable="true" width="auto" style="font-family:'Ubuntu';text-align:center;"></th>
                        <th class="contenteditable" contenteditable="true" width="21%" style="font-family:'Ubuntu';text-align:center;"></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- ITEMS HERE -->
                    <!--            ##productlist_start##-->
                    <tr>
                        <td class="contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true">{{var items_name}}<br/>{{var items_product_options}}</td>
                        <td class="contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_price}}</td>
                        <td class="contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_qty}}</td>
                        <td class="contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="item" contenteditable="true" align="right">{{var items_row_total}}</td>
                    </tr>
                    <!--            ##productlist_end##-->
                </tbody>
            </table>
            <div class="bottom-table">
            </div>
        </div>

        <div class="totals contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="main" contenteditable="true">
            <div class="body-total autogrow" contextmenu-type="main" title="Click to edit, right-click to insert variable">
                <div class="total-row" title="Click to edit, right-click to insert variable">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Subtotal'); ?></div>
                    <div class="total-value color-text">{{var creditmemo_subtotal}}</div>
                </div>
                <div class="total-row" title="Click to edit, right-click to insert variable">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Tax'); ?></div>
                    <div class="total-value color-text">{{var creditmemo_tax_amount}}</div>
                </div>
                <div class="total-row" title="Click to edit, right-click to insert variable">
                    <div class="total-label color-text"><?php echo $this->_locale->translate('Shipping'); ?></div>
                    <div class="total-value color-text">{{var creditmemo_shipping_amount}}</div>
                </div>
                <div class="total-row total-row-grand" title="Click to edit, right-click to insert variable">
                    <div class="total-label color-text grand-total"><?php echo $this->_locale->translate('Grand Total'); ?></div>
                    <div class="total-value color-text grand-total grand-total-value">{{var creditmemo_grand_total}}</div>
                </div>
            </div>
        </div>

        <div contextmenu-type="main" class="note-box contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true" contextmenu-type="order">
            <?php if ($note): ?><div class="note p-note color-text"><strong>Note:</strong><div info-text="note"> <?php echo $note; ?></div></div> <?php endif; ?>
        </div>
        <div contextmenu-type="main" class="bottom-totals autogrow contenteditable" title="Click to edit, right-click to insert variable" contenteditable="true">
            <div info-text-outer="company_telephone"><?php if ($phone): ?><p class="info-company_email general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('Tel: '); ?></span><span info-text="company_telephone"><?php echo $phone ?></span></p><?php endif; ?></div>
            <div info-text-outer="company_fax"><?php if ($fax): ?><p class="info-vat_number general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('Fax: '); ?> </span><span info-text="company_fax"><?php echo $fax ?></span></p><?php endif; ?></div>
            <div info-text-outer="company_email"><?php if ($email): ?><p class="info-company_email general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('Email: '); ?></span><span info-text="company_email"><?php echo $email ?></span></p><?php endif; ?></div>
            <div info-text-outer="vat_number"><?php if ($vatnumber): ?><p class="info-vat_number general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('VAT Number: '); ?> </span><span info-text="vat_number"><?php echo $vatnumber ?></span></p><?php endif; ?></div>
            <div info-text-outer="vat_office"><?php if ($vatoffice): ?><p class="info-vat_number general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('VAT Office: '); ?> </span><span info-text="vat_office"><?php echo $vatoffice ?></span></p><?php endif; ?></div>
            <div info-text-outer="business_id"><?php if ($businessId): ?><p class="info-vat_number general-info" title="Click to edit, right-click to insert variable" style="pading: 0; margin: 0;"><span><?php echo $this->_locale->translate('Business ID: '); ?> </span><span info-text="business_id"><?php echo $businessId ?></span></p><?php endif; ?></div>
        </div>
        <div contextmenu-type="main" class="term-conditions">
            <p class="barcode-order contenteditable" title="Click to edit, right-click to insert variable" contextmenu-type="main" contenteditable="true" info-text="terms_conditions"><?php echo $term; ?></p>
        </div>
    </div>

</div>

        <div id="footer" contextmenu-type="main" class="footer-template06 color-text" name="myfooter" style="height: <?php echo $footerHeight;?>px;">
            <div contenteditable="true" title="Click to edit, right-click to insert variable" class="footer-text bottom-color contenteditable" style="padding-top: 10px;width: 100%;" info-text="footer">
                <?php if ($footer) echo $footer; ?>
            </div>
        </div>
    <script type="text/javascript">
//        $(function() {
//            if ($('#footer').length > 0) {
//                var footer = $('#footer').height() +30;
//                $('#container-a6').css('padding-bottom', footer + 'px');
//            }
//        });
    </script>
